define([],function(){
var exports = {
//////////////////////////////////
// Enter each key value pair as //
// "key" : "value" ,            //
//////////////////////////////////
// Do not edit above this line  //
//////////////////////////////////
"unspecified": "Unspecified",
"yes": "Yes",
"no": "No",
"error.notify": "An error has occurred. Please contact your plan administrator.",
"error.application": "Error: 500",

"english": "English",
"french": "French",

"m": "Male",
"f": "Female",

"smoker": "smoker",
"non-smoker": "non-smoker",

"spouse": "Spouse",
"child": "Child",
"other": "Other",
"title.enrolment": "", //"Enrolment",
"title.reenrolment": "", //"Re-Enrolment",
"title.lifeEvents": "", //"Life events",

"select": "Select",
"download": "Download",
"start": "Start",
"default": "(Default)",
"loading": "Loading",
"administrator": "Administrator",
"mm.dd.yyyy": "mm/dd/yyyy",
"save.changes": "Save changes?",

"Optional": " (optional)",

"Alberta": "Alberta",
"British_Columbia": "British Columbia",
"Manitoba": "Manitoba",
"New_Brunswick": "New Brunswick",
"Newfoundland_and_Labrador": "Newfoundland and Labrador",
"Northwest_Territories": "Northwest Territories",
"Nova_Scotia": "Nova Scotia",
"Nunavut": "Nunavut",
"Ontario": "Ontario",
"Prince_Edward_Island": "Prince Edward Island",
"Quebec": "Quebec",
"Saskatchewan": "Saskatchewan",
"Yukon": "Yukon",

"required.fields": "Required fields",
"required.fields.asterisk": "Required fields",
"required.field": "Required fields",
"required.fieldsErrorText": "This field is required.",
"required.valid.date": "Please enter a proper date in mm/dd/yyyy format",
"required.valid.number": "Please enter a number",

"hello":"Hello world!",
"copyright":"&copy; 2013 Benpal",

/*"footer.copyright": "Copyright 2014 Jardine Lloyd Thompson Group plc", */  // Removed by FJ
"footer.copyright": "Copyright 2014 Jardine Lloyd Thompson Group plc",  //  Added by FJ
"footer.contactUs": "Contact us",
"footer.support": "Support",
"footer.supportAndDocumentation": "Support and documentation",
"footer.legalInformation": "Legal information",
"footer.termsOfUsage": "Terms and conditions",
"footer.privacyStatement": "Privacy statement",
"footer.powered": "Powered",
"footer.by": " by",
"footer.accessibility": "Accessibility",
"footer.privacy": "Privacy",
"footer.termsOfUse": "Terms and conditions",

"contact.us.flexible.benefits.program": "Questions for your <b>'flexible benefits program'</b>",
"contact.us.flexible.benefits.program.phone": "514-787-2088 or 1-877-599-FLEX (3539)",
"contact.us.flexible.benefits.program.email": "Email address : flex@manulife.com",
"contact.us.claims": "Questions related to <b>'claims'</b>",
"contact.us.claims.phone": "514-841-5311 or 1-800-499-4415",
"contact.us.claims.email": "Email address : group.medent@standardlife.ca",

"welcome.greeting": "Login information",
"welcome.enroll": "Your plan. Your choice.", //"",
"welcome.enrollAndSelect": "Enroll and select your Plan choices in a few easy steps.",
"welcome.enrollText1": "Your flexible  group insurance benefit plan is an important feature of your overall compensation package and provides essential protection for you and your family",
"welcome.enrollText2": "Your flexible  group insurance benefit plan is an important feature of your overall compensation package and provides essential protection for you and your family",
"welcome.enrollNow": "Choose Now",
"welcome.reEnroll": "Your benefits. Your way.", //"It's Time to Re-enroll ...",
"welcome.reEnroll.available.from": "Available from ",
"welcome.reEnroll.available.to": "to ",
"welcome.reEnroll.available.end": "",
"welcome.reEnrollText1": "Your flexible  group insurance benefit plan is an important feature of your overall compensation package and provides essential protection for you and your family",
"welcome.reEnrollText2": "Your flexible  group insurance benefit plan is an important feature of your overall compensation package and provides essential protection for you and your family",
"welcome.reEnroll.review": "Choose now",

"calendar.monday": "Monday",
"calendar.thursday": "Thursday",
"calendar.wednesday": "Wednesday",
"calendar.tuesday": "Tuesday",
"calendar.friday": "Friday",
"calendar.saturday": "Saturday",
"calendar.sunday": "Sunday",

"calendar.january": "January",
"calendar.february": "February",
"calendar.march": "March",
"calendar.april": "April",
"calendar.may": "May",
"calendar.june": "June",
"calendar.july": "July",
"calendar.august": "August",
"calendar.september": "September",
"calendar.october": "October",
"calendar.november": "November",
"calendar.december": "December",

"calendar.clearDate": "Clear date",
"calendar.today": "Today",

"header.supportDocumentation": "Support & documentation",
"header.about": "About",
"header.legal": "Legal",
"header.logout": "Log out",
"header.contact": "Contact",
"header.tutorial": "Tutorial",
"header.planWorkbook": "Plan workbook",
"header.glossary": "Insurance glossary",
"header.faq": "Frequently asked questions",


"login": "Login",
"login.username": "User ID",
"login.password": "Password",
"login.forget.label": "Forgot ",
"login.forget.username": "user ID",
"login.forget.password": "password",
"login.rules.rule1": "Must be a minimum of ?1 characters long",
"login.rules.rule2": "Must contain letters, numbers and one or more of the following symbols ~!@##$%^&*",
"login.rules.rule3": "Must not be the same as your user ID",
"login.questions.wrongcredentials": "A missing piece of information in your file is preventing your request from being successfully completed. Please verify with your Plan Administrator.",
"login.questions.invalid": "You did not answer the questions correctly. Please contact your plan administrator to complete your request.",
"login.error.wrong.passwdusrname": "Incorrect password or user ID",
"login.error.locked.numofloginlimit": "You have entered an incorrect password ?1 times, your access to the system has been locked. Please contact your plan administrator to unlock your file.",

"change.password": "Change password",
"change.my.password": "Change my password",
"change.password.new.password": "Enter your new password : ",
"change.password.re.new.password": "Re-enter your new password : ",
"renewpassword.passwdhistory": "You must not use any of your previous 10 passwords",
"renewpassword.passwdnosession": "Session expired",
"renewpassword.passwdnousernamemirror": "New password must not be a copy of the user ID",
"renewpassword.passwdminlength": "New Password can not be less than 8 characters",
"renewpassword.passwdchanged": "The password was changed",
"renewpassword.passwdwrongoldpassword": "Wrong current password",
"password.enterYourCurrentPassword": "Enter your current password : ",
"password.enterYourNewPassword": "Enter your new password : ",
"password.reEnterYourNewPassword": "Re-enter your new password : ",

"forgotten.username.greeting": "Forgot user ID",
"forgotten.username.firstname": "First name",
"forgotten.username.lastname": "Last name",
"forgotten.username.birthday": "Birth date",
"forgotten.username.email": "Email",
"forgotten.username.successMsg": "Email with your user name has been sent to your email address",
"forgotten.username.dateValidationMsg": "The Date should be put in mm/dd/yyyy format",

"forgotten.password.greeting": "Forgot password",
"forgotten.password.username": "User ID",
"forgotten.password.email": "Email",
"forgotten.password.security.questions.header": "Please, answer the following security questions and click submit",
"forgotten.password.tempLogin.notification.tempPass": "Please note and write down your new temporary password : ",
"forgotten.password.tempLogin.notification.requiredAction": "You will be required to enter it again later in order to change this temporary password once you log in.",
"forgotten.password.tempLogin.notification.login": "Please login below.",
"forgotten.password.renew.header": "Please renew your password below.",
"forgotten.password.renew": "Renew password",
"forgotten.password.tempPassword": "Temp password",
"forgotten.password.new.password": "New password",
"forgotten.password.confirm.new.password": "Confirm new password",
"forgotten.password.wrong.temp.password": "Temp password is incorrect.",

"forgotten.credentials.backtologin": "Back to login page",
"forgotten.credentials.errorMsg": "A missing piece of information in your file is preventing your request from being successfully completed. Please verify with your Plan Administrator.",
"uname.recover.message": "A missing piece of information in your file is preventing your request from being successfully completed. Please verify with your Plan Administrator.",

"date.format": "mm/dd/yyyy",
"cancel":"Cancel",
"continue": "Continue",
"back": "Back",
"save": "Save",
"reset": "Reset",
"save.continue": "Save and continue",
"edit": "Edit",
"details": "Details",
"notes": "Notes",
"submit": "Submit",
"none": "None",
"home": "Home",
"submit.enrolment": "Submit enrolment",
"submit.lifeEvent": "Submit life event",

"change.password.header": "Please make these important changes to your profile before proceeding.",
"change.password.error.not.matching": "Passwords are not matching",
"change.password.error.not.valid": "Password should contain at least 1 number and 1 character",
"change.password.rules": "Password requirements",

"security.questions": "Security Questions",
"security.questions.question.1": 'What was the make of your first car?',
"security.questions.question.2": 'What was the name of your elementary school?',
"security.questions.question.3": "What is your mother's maiden name?",
"security.questions.question.4": 'What is your favourite dessert?',
"security.questions.question.5": 'What is your favourite animal?',
"security.questions.question.6": 'What is the name of a destination you would like to visit?',
"security.questions.question.7": 'What was the name of your first employer?',
"security.questions.question.8": 'What was the name of your first girlfriend/boyfriend?',
"security.questions.question.9": 'Who is your favourite actor/actress?',
"security.questions.question.10": 'What is the name of your favourite movie?',
"security.questions.question.11": 'What sport do you practice or would you like to practice?',
"security.questions.question.12": 'What is your favourite colour?',
"security.questions.error.unique": "All questions should be unique",

"enrollNow.personal.info": "Personal information",
"enrollNow.my.profile": "My profile",
"enrollNow.dependents": "My dependents",
"enrollNow.personal.verifyText": 'Please verify that your information is correct. If any information is incorrect contact your Human Resources representative before proceeding.',
"enrollNow.benefits": "My benefits",

"enrollNow.costs": "My summary",

"enrollNow.congratulations": "Congratulations",

"enrollNow.unusedCredits": "My credits",

"enrollNow.personal.birthday": "Birth date : ",
"enrollNow.personal.gender": "Gender : ",
"enrollNow.personal.languagePreference": "Language preference : ",
"enrollNow.personal.effectiveDate": "Effective date : ",
"enrollNow.personal.zip.postal.code": "Postal code : ",
"enrollNow.personal.sin": "SIN : ",
"enrollNow.personal.hireDate": "Hire date : ",
"enrollNow.personal.class": "Class name : ",
"enrollNow.personal.certificateNumber": "Certificate number : ",
"enrollNow.personal.planAdministrator": "Plan administrator : ",
"enrollNow.personal.position": "Position : ",
"enrollNow.personal.langPreference": "Language for correspondence : ",
"enrollNow.personal.ruSmoker": "Are you a smoker? ",
"enrollNow.personal.division": "Division name : ",
"enrollNow.personal.address": "Address",
"enrollNow.personal.street": "Street : ",
"enrollNow.personal.aptUnit": "Apt/Unit : ",
"enrollNow.personal.charactersLimit": "Maximum of 50 characters per line",
"enrollNow.personal.city": "City : ",
"enrollNow.personal.zipPostalCode": "Postal code : ",
"enrollNow.personal.zipPostalCodeNote": "No spaces or dashes allowed (ex A1A1A1)",
"enrollNow.personal.stateProvince": "State/Province : ",
"enrollNow.personal.stateProvinceChange": "If you changed state/province of residence please enter effective date ",
"enrollNow.personal.phoneInfo": "Phone numbers and email : ",
"enrollNow.personal.smokingStatus": "Smoking status",
"enrollNow.personal.nonSmokerDefinition": "Non-Smoker definition",
"enrollNow.personal.haveNotSmoked.text1": "Non-smoker definition: Have not smoked cigarettes or cigarillos during the 12 months preceding the date of signature of the application. ",
"enrollNow.personal.haveNotSmoked.text2": "For a complete definition, consult your",
"enrollNow.personal.groupInsuranceBooklet": "Group insurance booklet",
"enrollNow.personal.currentSmokerStatus": "Your current smoker status is : ",
"enrollNow.personal.lastEffectiveDate": "Last effective date : ",
"enrollNow.personal.newSmokerStatus": "New smoker status : ",
"enrollNow.personal.newEffectiveDate": "New effective date : ",
"enrollNow.personal.smokingStatusText": "When you enroll, you will need to specify whether you are a smoker or non-smoker. To be considered a non-smoker, you must have not used any tobacco products for at least twelve continuous months prior to enrolling",
"enrollNow.personal.homePhoneNum": "Home phone number : ",
"enrollNow.personal.cellPhoneNum": "Cell phone number : ",
"enrollNow.personal.emergContactName": "Emergency contact name : ",
"enrollNow.personal.emergContactNumber": "Emergency contact number : ",
"enrollNow.personal.email": "Email : ",
"enrollNow.personal.busPhoneNumber": "Work phone number : ",
"enrollNow.personal.extension": "Extension : ",
"enrollNow.personal.employmentInfo": "Employment information",
"enrollNow.personal.policyholder": "Policyholder : ",
"enrollNow.personal.provinceOfEmplyment": "Province of employment : ",
"enrollNow.personal.policyNumber": "Policy number : ",
"enrollNow.personal.divisionNumber": "Division number : ",
"enrollNow.personal.classNumber": "Class number : ",
"enrollNow.personal.costCenter": "Cost center : ",
"enrollNow.personal.username": "User ID : ",
"enrollNow.personal.employeeNumber": "Employee number : ",
"enrollNow.personal.dependentStatus": "Dependent status : ",
"enrollNow.personal.bankingInfo": "Banking Info",
"enrollNow.personal.bankAccountNumber": "Account : ",
"enrollNow.personal.institutionNumber": "Institution : ",
"enrollNow.personal.bankTransitNumber": "Transit : ",
"enrollNow.personal.viewSampleCheck": "View Sample Check",
"enrollNow.personal.directDepositText": "I wish to use direct deposit to my bank account for any claims reimbursement.",

"enrollNow.personal.phoneNumberValidation": "The home phone number should be valid",
"enrollNow.personal.cellPhoneNumberValidation": "The cellphone number should be valid",
"enrollNow.personal.busPhoneNumberValidation": "The bus. phone number should be valid",
"enrollNow.personal.busPhoneNumberExtensionValidation": "The extension number should be valid",
"enrollNow.personal.emergNumberValidation": "The emergency contact's phone number should be valid",
"enrollNow.personal.addressEffectiveDateValidation": "The Date should be valid and be put in mm/dd/yyyy format",
"enrollNow.personal.addressEffectiveDateValidationMoreThanEqualToday": "The Date should be more then equal then today's date",
"enrollNow.personal.addressEffectiveDateValidationLessThanEqualToday": "The Date should be less then equal then today's date",

"enrollNow.personal.bankAccountNumberValidation": "The bank account should contain only numbers (up to 20 digits)",
"enrollNow.personal.institutionNumberValidation": "The institution transit number should contain only numbers (3 digits)",
"enrollNow.personal.bankTransitNumberValidation": "The bank transit number should contain only numbers (5 digits)",
"enrollNow.personal.emergNameValidation": "The contact name should be valid",
"enrollNow.personal.smokerValidation": "You must specify your smoker status",

"enrollNow.personal.directDeposit.title": "Direct deposit",
"enrollNow.personal.directDeposit.5digits": "5 digits",
"enrollNow.personal.directDeposit.3digits": "3 digits",

"dependents": "Dependents",
"dependents.definition": 'List your dependents and enter their personal information. Pay close attention to information regarding your spouse’s smoking habits.',
"dependents.definitionTitle": 'List your dependents and enter their personal information. Pay close attention to information regarding your spouse’s smoking habits.',
"dependents.name": "Name",
"dependents.type": "Type",
"dependents.discontinueCoverage": "Terminate coverage",
"dependents.addDependent": "Add a dependent",
"dependents.editDependent": "Edit",
"dependents.relationship": "Relationship : ",
"dependents.effectiveDate": "Effective date : ",
"dependents.firstName": "First name : ",
"dependents.lastName": "Last name : ",
"dependents.gender": "Gender : ",
"dependents.birthDate": "Birth date : ",
"dependents.ssnsin": "SIN : ",
"dependents.coveredElsewhere": "Is the dependent covered elsewhere?",
"dependents.noSpaces": "No spaces",
"dependents.discontinue.message": "Are you sure you want to discontinue?",
"dependents.terminated.awaiting.approval": "Request to discontinue coverage has been submitted.",
"dependents.terminsched.awaiting.approval": "Coverage termination has been scheduled for ...",
"dependents.insurerName": "Insurer name",
"dependents.policyNumber": "Policy number",
"dependents.doesMedicalCoverage": "Is this person covered for health care?",
"dependents.doesDentalCoverage": "Is this person covered for dental care?",
"dependents.atLeastOneField": "At least one of the Health and Dental indicators must be set to Yes",
"dependents.smoker": "Is dependent a smoker?",
"dependents.smoker.notAvailable": "N/A",
"dependents.discontinue.confirm": "Confirm discontinue coverage",
"dependents.no.dependent": "There is no dependent registered in your file",
"dependents.cancelConfirmation": "If you entered any data, it will be lost",
"dependents.status": "Status",
"dependent.status.active": "Active",
"dependent.status.pending": "Pending",
"dependent.status.awaiting_approval": "Pending approval",

"benefits.Selections": "Benefit selections",
"benefits.mySelections": "My benefits",
"benefits.descriptionPart1": "For each benefit, you must indicate your choice by clicking on the button next to the name of option you wish to choose.",
"benefits.descriptionPart2": "If you need more information about a benefit, click on Benefit Info or refer to the enrolment kit you received.",
"benefits.MakeChanges": "Your existing enrolment choices are selected by default. Please scroll down through the benefit options and make any changes as you see fit.",
"benefits.dentalInsurance": "Dental Insurance",
"benefits.health": "Health",
"benefits.dental": "Dental",
"benefits.life": "Life",
"benefits.disability": "Disability",
"benefits.costCalculator": "Cost calculator",
"benefits.optionalBenefits": "Optional Benefits",
"benefits.optionalBenefits.participantSpouseLife": "Partisipant Spouse Life",
"benefits.optionalBenefits.participantSpouseIllness": "Partisipant Spouse Illness",
"benefits.monthlyCredits": "Monthly credits",
"benefits.availableCredits": "Available credits",
"benefits.usedCredits": "Used credits",
"benefits.balancePayroll": "Balance (+) Payroll deduction (-)",
"benefits.used": "Used",
"benefits.remaining": "Remaining",
"benefits.employerPaidCosts": "Employer paid costs",
"benefits.employerPaidCost": "Employer paid cost",
"benefits.monthlyCost": "Monthly cost",
"benefits.benefitCost": "Cost",
"benefits.employerShare": "Employer share",
"benefits.amount": "Amount",
"benefits.yourShareFC": "Flexible credits",
"benefits.yourSharePD": "Payroll deductions",
"benefits.yourSharePD.requested": "Payroll deductions",
"benefits.yourSharePD.approved": "Payroll deductions",
"benefits.monthlyPayrollDeduction": "Monthly payroll deductions",
"benefits.monthlyPayrollDeductionHint": "Hint",
"benefits.monthlyPayrollDeductionInfo": "If you have selected a coverage that requires evidence of insurability, the coverage you requested will be pending until approval is given but the “After approval” amount will include the cost of the requested coverage. In the meantime, the maximum allowed without evidence of insurability will be applied and reflected in the “Before approval” amount.",
"benefits.beforeApproval": "Before approval",
"benefits.afterApproval": "After approval",
"benefits.PdBeforeApproval": "Payroll deductions Before Approval",
"benefits.PdAfterApproval": "Payroll deductions After approval",
"benefits.paymentText": "Lorem ipsum dolor sit amet ctetur adipiscing elit. Donec pharetra risus eu justo vulputate pretium. Lorem ipsum dolor sit amet ctetur adipiscing elit. Donec pharetra risus eu justo vulputate pretium.",
"benefits.paymentMethod": "Payment method",
"benefits.flexCredits": "Flexible credits",
"benefits.payrollDeduction": "Payroll deductions",
"benefits.options": "Options",
"benefits.coverage.grade": "Coverage level",
"benefits.coverage": "Coverage",
"benefits.requested.coverage": "Requested coverage",
"benefits.requested.coverage.amount": "Requested coverage amount",
"benefits.my.coverage": "My coverage",
"change.my.benefits": "Change my benefits",
"keep.same.selection": "Keep the same selections",
"view.coverage.history": "View coverage history",
"benefits.yourShare": "Your share",
"benefits.approved.coverage.amount": "Approved coverage amount",
"benefits.approved.coverage": "Approved coverage",
"benefits.approved.cost": "Approved cost",
"benefits.optionA": "Option A",
"benefits.optionB": "Option B",
"benefits.optionC": "Option C",
"benefits.optionOptOut": "Opt Out",
"benefits.dropdown.employee": "Employee",
"benefits.dropdown.employeePlusOne": "Employee + 1",
"benefits.dropdown.employeePlusFamily": "Employee + Family",
"benefits.option.not.selected.warning": "Please select benefit option to Save & Continue.",
"benefits.coverage.not.selected.warning": "Please select benefit option coverage to Save & Continue.",
"benefits.option.paymentMethod.not.selected.warning": "Please select Benefit Option Payment Method to Save & Continue.",
"benefits.option.minMaxRangeValidation": "Selected contribution value must be within the specified range",
"benefits.leaveConfirmation":"All data entered on this page will be lost, do you wish to continue?",
"benefits.select.higher.option": "In order to select this option, you have to select the highest option for ?1",
"benefits.credits": "credits",
"benefits.credits.allowed": "Allocated credits",
"benefits.used.one": "Used",
"benefits.balance": "Balance",
"benefits.employer.share": "Employer share",
"benefits.payroll.deduction": "Payroll deductions",
"benefits.payroll.deduction.before.approval": "payroll deduction (before approval)",
"benefits.payroll.deduction.after.approval": "payroll deduction (after approval)",
"benefits.wasSelected": "Was previously selected",

"unusedCredits.headerText": "Lorem ipsum dolor sit amet ctetur adipiscing elit. Donec pharetra risus eu justo vulputate pretium. Lorem ipsum dolor sit amet ctetur adipiscing elit. Donec pharetra risus eu justo vulputate pretium.",
"unusedCredits.flexCreditAllocation": "Flexible credit allocation",
"unusedCredits.flexTitle1": "You have ",
"unusedCredits.flexTitle2": " remaining monthly credits. You must allocate these credits before submitting your enrolment. The following options are available ",
"unusedCredits.retirementProgram": "Retirement Program",
"unusedCredits.healthSpendingAccountHSA": "Health Spending Account (HSA)",
"unusedCredits.cash": "Cash",
"unusedCredits.retirementProvider": "Retirement Provider 1",
"unusedCredits.unallocatedCredits": "Unallocated Credits (must equal 0)",
"unusedCredits.numberValidationErrorText": "Please enter a number greater than 0",
"unusedCredits.leaveConfirmation": "All data entered on this page will be lost, do you wish to continue?",
"unusedCredits.minCredit": "Please enter a number greater than ?1",

"scenario.summary": "Summary",
"scenario.headerText1": "Before committing to your final choices, you may save up to three plan scenarios for comparison.",
"scenario.headerText2": "To edit a scenario select any of the benefit choices.",
"scenario.scenario": "Scenario",
"scenario.addScenario": "Add",
"scenario.close": "Close Scenario",
"scenario.selectedScenario": "Selected Scenario",
"scenario.available": "Available",
"scenario.used": "Used",
"scenario.balance": "Balance",
"scenario.coreCoverage": "Core Coverage",
"scenario.dependentLife": "Dependent Life",
"scenario.criticalIllnesses": "Critical Illnesses",
"scenario.shortTermDisability": "Short Term Disability",
"scenario.longTermDisability": "Long Term Disability",
"scenario.employerPaidCostsMonthly": "Employer paid costs (Monthly)",
"scenario.payrollDeductionMonthly": "Payroll deduction (monthly)",
"scenario.scenarioSelected": "Scenario selected",
"scenario.submitSelections": "Submit selections",
"scenario.coverageSelection.date.range.from": "Coverage selections are from",
"scenario.coverageSelection.date.range.to": "to",
"scenario.headerText3": "Lorem ipsum dolor sit amet ctetur adipiscing elit. Donec pharetra risus eu justo vulputate pretium. In placerat tempus felis, vitae interdum enim laoreet nec. Donec pharetra risus eu justo vulputate pretium.",
"scenario.removeScenario.confirmMsg": "Are you sure you want to remove scenario",
"scenario.removing.confirm": "Confirm Removing Scenario",

"splash.welcome.BP": "Employee login",
"splash.significantLifeEvent": "Did you have a significant life event since you last reviewed or selected your flexible benefits",
"splash.viewReadonlyBenefits": "View benefits",
"splash.matrimonialChange": "Matrimonial change",
"splash.additionDependent": "Addition of a Dependent/Child",
"splash.removalDependent": "Removal of a Dependent/Child",
"splash.spouseCoverageModification": "Spouse Coverage Modification",
"splash.other": "Other",
"splash.matrimonialEffectifeDate": "Matrimonial change effective date",
"splash.updateMaritalStatus": "Update Marital Status",
"splash.additionDependentChildEffectiveDate": "Add Dependent/Child Efective Date",
"splash.addDependentChildEffectiveDate": "Add Dependent/Child Effective Date",
"splash.addDependentChild": "Add Dependent/Child",
"splash.removeDependentChildEffectiveDate": "Remove Dependent/Child Effective Date",
"splash.removeDependentChild": "Remove Dependent/Child",
"splash.additionSpouseEffectiveDate": "Add Spouse Coverage Modificatoin Efective Date",
"splash.updateadditionSpouse": "Add Spouse Coverage Modificatoin",
"splash.additionOtherEffectiveDate": "Add Other efective Date",
"splash.updateadditionOther": "Add other",
"splash.lifeEvents.maxPeriodExceeded.warning": "Max period is exceeded.",
"splash.lifeEvents.maxPeriodExceeded.error.title": "Error (max period)",
"splash.lifeEvents.maxPeriodExceeded.error.message": "The requested Life event effective date exceeds the allowed period. Please consult your plan administrator.",
"splash.lifeEvents.preCurrentCoverage.error.title": "Error: Effective date precedes enrolment",
"splash.lifeEvents.preCurrentCoverage.error.message": "The requested Life event effective date precedes a coverage date already in place. Please consult your plan administrator.",
"splash.lifeEvents.gracePeriodExceeded.warning.title": "Warning: Grace period",
"splash.lifeEvents.gracePeriodExceeded.warning.message": "The requested Life event will have to be approved by the plan administrator.",

"healthSpendingAccountHSA": "Health Spending Account (HSA)",
"cash": "Cash",
"retirementProvider": "Retirement Provider 1",
"unusedCredits.unallocatedCreditsYouHave": "You have unallocated flexible credits : ",
"unusedCredits.unallocatedCreditsOverSpent": "You have overspent your credits by : ",

"coverage.history": "Coverage history",
"coverage.history.plan": "Plan",
"coverage.history.plan.type": "Type",
"coverage.history.plan.last.modified": "Last Modified",

"summary": "Plan selections spending summary",
"summary.definition.title.from": "Coverage selections are from",
"summary.definition.title.to": "to",
"summary.definition": "Lorem ipsum dolor sit amet ctetur adipsiccing elit. Donec pharetra risus eu justo vulputate pretium. Lorem ipsum dolor sit amet ctetur adipsiccing elit. Donec pharetra risus eu justo vulputate pretium.",

"summary.allocated": "Monthly Flexible credits allocated : ",
"summary.used": "Used : ",
"summary.remaining": "Remaining : ",
"summary.benefit": "Benefit",
"summary.totalCost": "Total Cost",
"summary.flexCreditsSpent": "Flexible credits spent",
"summary.employerShare": "Employer share",
"summary.yourShare": "Your share",
"summary.payrollDeductions": "Payroll deductions",
"summary.payrollDeductionsAfterApproval": "Payroll deductions after approval",
"summary.health": "Health",
"summary.dental": "Dental",
"summary.life": "Life",
"summary.disability": "Disability",
"summary.total": "Total",
"summary.yourLeftOverAllocated": "Your left over flexible credits have been allocated to : ",
"summary.RRSP": "RRSP",
"summary.HSA": "HSA",
"summary.finalizationAcceptance": "Finalization and Acceptance",
"summary.Disclaimer": "Disclaimer",
"summary.declare.reading": "I declare to have read the text above and I accept all the terms and condition. Select the checkbox if you agree and want to submit your selections",
"summary.declare.reading.accept": "I declare that I have read the text above and accept all terms and conditions",
"summary.hereby.accept": "I hereby accept the conditions...",
"summary.confirm.message": "By clicking OK your benefit selections will be submitted and your enrolment period will be closed.",

"summary.reenroll": "Coverage comparison",
"summary.reenroll.description": "Below is the coverage comparison for the two enrolment periods. For the new period, you can keep or change your current choices.",
"summary.reenroll.keep.selections": "Keep my current coverage",
//"summary.reenroll.keep.selections.description": "This action will bring you to the My summary step",
"summary.reenroll.modify.selections": "Modify my choices",
//"summary.reenroll.modify.selections.description": "This action will allow you to change your selections",

"congratulations": "Congratulations",
"congratulations.text1": "Congratulations !",
"congratulations.text2": "Your enrolment is now <strong>submitted</strong>",
"congratulations.lifeEvent.text2": "Your life event is now <strong>submitted</strong>",
"congratulations.text4": "Once your enrolment is approved, you will receive a confirmation email including information regarding your coverage’s effective date and the actions you must take.", // When your enrolment will be approved, you will receive a confirmation by email with indications about your coverage effective date, action to take, etc.
//"congratulations.lifeEvent.text4": "",	// When your life event will be approved, you will receive a confirmation by email with indications about your coverage effective date, action to take, etc.
"congratulations.text5": "If you need to perform a modification in your selections, please consult your plan administrator.",
"congratulations.benefit.summary.form": "You can download this benefit summary for your files.",
"congratulations.benefit.summary.available": "The benefit summary is also available under My coverage > Benefit summary.",
"congratulations.beneficiary.designation.form": "Beneficiary designation form",
"congratulations.evidence.insurability.form": "Evidence of insurability form",
"congratulations.critical.illness.form": "Evidence of insurability for Critical illness",
"congratulations.RRSP.form": "Group Registered Retirement Savings Plan (RRSP) form",
"congratulations.benefit.summary.PDF": "Benefit summary (PDF)",
"congratulations.benefits.designation.PDF": "Benefits Designation (PDF)",
"congratulations.evidence.insurability.PDF": "Evidence of Insurability (PDF)",
"congratulations.critical.illness.PDF": "Critical illness form (PDF)",
"congratulations.RRSP.PDF": "RRSP form (PDF)",
"congratulations.print.form": "Print form",
"congratulations.send.to.email": "Send form to my email  address",
"congratulations.download.summary": "Download my summary",
"congratulations.download.form": "Download form",
"congratulations.benefits.summary.PDF": "Benefits Summary (PDF)",
"congratulations.benefits.summary.temporary": "Benefits summary (temporary)",
"congratulations.actions.required.header": "Next steps",
"congratulations.actions.required.text": "According to your selections, some actions are required : ",
"congratulations.actions.email.subject.beneficiary": "Benificiary file subject line",
"congratulations.actions.email.subject.evidence": "Evidence file subject line",
"congratulations.actions.email.subject.rsp": "RSP file subject line",
"congratulations.actions.email.send.success": "Email sent successfully",
"congratulations.actions.email.send.failure": "Failed to send email",
"congratulations.beneficiary.designation.form.description": "If modification is needed, you have to complete, sign and send the form to plan administrator.",
"congratulations.enroll.beneficiary.designation.form.description": "You have to complete and sign the Beneficiary designation form and return it to your plan administrator.",
"congratulations.reEnroll.beneficiary.designation.form.description": "To modify your beneficiaries, please complete and sign the Beneficiary designation form and return it to your plan administrator.",
"congratulations.formsAreAvailable": "These forms are also available under Documentation > Forms",
"congratulations.actions.email.invalid": "Cannot email form, the email address for your account is improperly configured",

"coverage.my.coverage": "My coverage",
"coverage.unused.credits": "Unused credits",
"coverage.unallocated.credits": "Unallocated credits (balance)",
"coverage.enrolment.summary": "Enrolment summary",
"coverage.lifeEvent.summary": "Life event summary",
"coverage.life-events.summary": "My coverage",
"coverage.life-events.effective_date": "Effective date of coverage : ",
"coverage.life-events.coverage_status": "Coverage status : ",
"coverage.please.validate": "Please validate all information and submit your enrolment",
"coverage.lifeEvent.please.validate": "Please validate all information and submit your life event",
"coverage.my.history": "My history",
"coverage.your.benefit.coverage": "My benefit coverage",
"coverage.your.benefit.history": "Transactions",
"coverage.benefit.description": "Benefit description",
"coverage.option": "Option",
"coverage.coverage": "Coverage",
"coverage.benefit.cost": "Benefit Cost",
"coverage.employer.share": "Employer share",
"coverage.my.share": "My share",
"coverage.flex.credits": "Flexible credits",
"coverage.payroll.deduction": "Payroll deductions",
"coverage.life.ADD.insurane": "Life and AD&D Insurance",
"coverage.unapproved.amount": "(unapproved amount)",
"coverage.dependent.life.insuranec": "Dependent life insurance",
"coverage.optional.life.insurance": "Optional life insurance",
"coverage.spouse.optional.life.insurance": "Spouse optional life insurance",
"coverage.children.optional.life.insurance": "Children optional life insurance",
"coverage.optional.ADD.insurance": "Optional AD&D insurance",
"coverage.spouse.optional.ADD.insurance": "Spouse optional AD&D insurance",
"coverage.children.optional.ADD.insurance": "Children optional AD&D insurance",
"coverage.short.term.disability": "Short term disability",
"coverage.long.term.disability": "Long term disability",
"coverage.health.insurance": "Health insurance",
"coverage.dental.care": "Dental care",
"coverage.optional.critical.illness": "Optional critical illness (1)",
"coverage.employee.optional.critical.illness": "Employee optional critical illness (1)",
"coverage.spouse.optional.critical.illness": "Spouse optional critical illness (2)",
"coverage.total.cost": "Total cost",
"coverage.total.cost.unapproved.amounts": "Total cost including unapproved amounts",
"coverage.monthly.cost.summary": "My monthly cost summary",
"coverage.flexible.credits": "Flexible credits available",
"coverage.flex.credits.used": "Flexible fredits used",
"coverage.group.benefit.plan.cost": "Group benefit plan cost",
"coverage.balance.payroll.deduction": "Balance (+) / Payroll deduction (-)",
"coverage.cost.for.payroll.deduction": "Cost of benefit(s) paid for by payroll deductions",
"coverage.cost.by.payroll.deduction": "Cost by payroll deductions including unapproved amounts",
"coverage.total.cost.excluding.retail": "Total cost by payroll deductions (excluding applicable taxes)",
"coverage.total.cost.including.retail": "Total cost by payroll deductions including unapproved amounts (excluding applicable taxes)",
"coverage.unused.flex.credits.distribution": "My unused flexible credits allocation",
"coverage.balance.flex.credits": "Balance flexible credits",
"coverage.cash": "Cash",
"coverage.health.spending.account": "Health Spending Account (HSA)",
"coverage.group.registered.savings": "Group Registered Retirement Savings Plan (RRSP)",
"coverage.registered.pension.plan": "Registered Pension Plan (RPP)",
"coverage.group.tax.free": "Group Tax-Free Savings Account (TFSA)",
"coverage.total.employer.contribution": "Total Employer Contribution",
"coverage.total.employer.contribution.plan": "Total employer contribution to your benefit plan",
"coverage.taxable.benefits.provincial": "Taxable benefits (provincial)",
"coverage.taxable.benefits.federal": "Taxable benefits (federal)",

"coverage.life.event": "Life event",
"coverage.enrolment": "Enrolment",
"coverage.initial.enrolment": "Initial enrolment",
"coverage.enrolment.type": "Transaction type",
"coverage.effective.date.coverage": "Effective date",
"coverage.enrolment.period": "Enrolment period",
"coverage.authorized.on": "Authorized on",
"coverage.authorized.by": "Authorized by",
"coverage.benefit.summary.conf.stat": "Benefit summary",
"coverage.current.coverage": "Current coverage",
"coverage.coverage.history": "Coverage history",

//re-enroll
"coverage.your.benefit.coverage.comparison": "My coverage comparison",
"coverage.monthly.cost.comparison": "My monthly cost comparison",
"coverage.unused.flex.credits.distribution.comparison": "My unused flexible credits comparison",
"coverage.comparison.current.period": "Current period",
"coverage.comparison.new.period": "New period",


// global
"flex.credits": "Flexible credits",
"payroll.deductions": "$",
"session.sessionexpired": "Your session has expired, please open a new session or contact your plan administrator",

// /login/passwd.cfc
"passwd.passwdnousernamemirror": "New password must not be a copy of the user ID",
"passwd.passwdminlength": "New Password can not be less than ?1 characters",
"passwd.passwdcomplex": "Password must be a combination of at least one or more letters, one or more numbers and one or more following symbols ~!@##$%^&*",
"passwd.passwdhistory": "You must not use any of your previous 10 passwords",

// /login/questions.cfc
"questions.wrongcredentials": "A missing piece of information in your file is preventing your request from being successfully completed. Please verify with your Plan Administrator.",
"questions.noquestionsfound": "No security questions found",

// /login/sponsquestions.cfc
"sponsquestions.noquestionsfound": "No security questions found",
"sponsquestions.errorsettingquestions": "A missing piece of information in your file is preventing your request from being successfully completed. Please verify with your Plan Administrator.",

// /myinfo/dependent.cfc
"dependent.requested.birthdate.change.from{}1.to{}2": "Dependent birth date was changed from ?1 to ?2",
"dependent.spousesmoker.changed.from{}1.to{}2": "Dependent smoker status was changed from ?1 to ?2",
"dependent.requested.is_smoker.change.from{}1.to{}2": "Employee requested change of spouse smoker status from ?1 to ?2",
"dependent.add.alreadyexist": "This dependent has already been added",
"dependent.add.reallocatedcredits": "Flexible credits allocated have been re-calculated and selections re-opened. Proceed to the Selections tab to perform selections.",
"dependent.awaiting.approval": "Pending approval",
"dependent.termindate.sched": "Termination of the coverage for this dependent is scheduled for ?1",
"dependent.smoker.sched": "Change of smoker status scheduled for ?1",
"dependent.termindate": "for coverage termination.",
"dependent.birthdate": "birthdate change.",
"dependent.approved.futuredate": "Your dependent will be effective ?1",

// /myinfo/employee.cfc
"employee.passwordcomplex": "Password must be a combination of at least one or more letters, one or more numbers and one or more following symbols ~!@##$%^&*",
"employee.passwminlength": "New Password can not be less than ?1 characters",
"employee.updatesecurityinfo.passwdempty": "Old Password is required",
"employee.updatesecurityinfo.passwdnew.dontmatch": "Do not match",
"employee.updatesecurityinfo.passwdnewempty": "New Password is required",
"employee.updatesecurityinfo.passwdnewshort": "New Password can not be less than ?1 characters",
"employee.updatesecurityinfo.passwmirror": "New password must not be a copy of the user ID",
"employee.updatesecurityinfo.passwdduplicate": "Old Password and New Password can not be the same",
"employee.updatesecurityinfo.passwdcomplex": "Password must be a combination of at least one or more letters, one or more numbers and one or more following symbols ~!@##$%^&*",
"employee.updatepersonalinfo.provterreffdatemissing": "Please specify effective date for the change of province of residence.",
"employee.updatepersonalinfo.provterreffdatepast": "Date for the change of province of residence must not be in the past.",
"employee.updatepersonalinfo.provterreffdatefuture": "Requested change of the state/province of residence is scheduled for ?1",
"employee.smokerstatus.waitapproval": "You or your spouse have requested a ?1 status effective ?2. Your request has been submitted for approval. Please contact your plan administrator for any questions.",
"employee.smokerstatus.change": "You can only change your smoker status once your life event is complete.",

// //selections/empselections.cfc
"empselections.benefagetermin.note": "Benefit coverage is terminated at the age of ?1",
"empselections.benefagereduct.note": "Benefit coverage is reduced at the age of ?1",
"empselections.benfwaiver.note": "Benefit is on waiver", 
"empselections.employee": "Employee",
"empselections.spouse": "Spouse",
"empselections.dependent": "Dependent",
"empselections.family": "Family",
"empselections.coverage.period.cost": "Coverage ?1 - ?2 cost: ?3 ?4",
"empselections.coverage.period.cost.min": "Coverage ?1 ?2",
"empselections.param.period.1": "Monthly",
"empselections.param.period.2": "Weekly",
"empselections.param.period.3": "Bi-Weekly",
"empselections.param.period.4": "Annualy",
"empselections.param.waived": "(Waived)",
"empselections.agereduct.note": "Coverage reduces to ?1 at the age of ?2",
"empselections.agetermin.note": "This option terminates its coverage at the age of ?1",
"empselections.requested": "Requested: ?1 - Monthly cost: ?2",
"empselections.approved": "Approved: ?1 - Monthly cost: ?2",

"empselections.prevselopt.note": "This option was previously selected with the ?1 ?2",
"empselections.prevenrollselopt.note": "Last enrolment year this option was selected ?1 ?2",
"empselections.param.prevselopt.s": "coverage of",
"empselections.param.prevselopt.def": "cost of",

//"empselections.evidreq.note": "To increase the coverage of this benefit, evidence of insurability will be required. Please verify with your plan administrator",
"empselections.nem_supported.note": "Warning – Evidence of insurability required</br></br>You have selected a coverage that requires evidence of insurability.  At the end of your enrolment, you will have to complete a form and submit your request to insurer. The requested coverage will be 'Pending' until approval is given by insurer.  The maximum allowed without evidence of insurability will be applied in the meantime.",
"empselections.nem_supported_details.note": "Coverage not yet approved by plan administrator and will not be reflected in the running total on the benefit and the plan summary: <br />Requested: ?1 - Monthly cost: ( ?4 )<br />Approved: ?5 - Monthly cost: ( ?6 )",
"empselections.nem_evidfile_details.note": "<a href=?1>Click here</a> to download the evidence documentation if you wish to increase your maximum coverage to the amount indicated.",

"empselections.fsacontrib": "Enter ?1 contribution amount",
"empselections.fsaminmaxcontrib": "Minimum contribution ?1 ?2, maximum contribution ?3 ?2",
"empselections.prevselectedoption.note": "This option was previously selected ?1 ?2",
"empselections.prevenrollmentselectedoption.note": "Last enrolment year this option was selected ?1 ?2",
"empselections.withcost": "with the cost of",

// /selections/unusedflexcredits.cfc
"selections.unusedflexcredits.param.1": "minimum contribution is ",
"selections.unusedflexcredits.param.3": "maximum contribution is ",
"selections.unusedflexcredits.cashlabel": "Cash ?1 ?2 ?3 ?4",
"selections.unusedflexcredits.hcsalabel": "Health Spending Account (HSA) ?1 ?2 ?3 ?4",
"selections.unusedflexcredits.rrsplabel": "?1 ?2 ?3 ?4",
"selections.unusedflexcredits.rrspfile": "(<a href='?1' target='_blank'>Download document</a>)",
"selections.unusedflexcredits.rrspselectyourprog": "Select ?1 as your retirement program carrier",
"selections.unusedflexcredits.unusedcreditslabel": "?1",
"selections.unusedflexcredits.unusedcreditsoptionslabel": "?1",

"life.derectDepositInfo": "Direct deposit",
"life.enjoyPeaceofMind": "You can enjoy peace of mind in knowing that your reimbursement will be directed into the designated account within three working days following the day your claim is processed, and you will continue to receive an explanation of benefit payment and notice of direct deposit.",
"life.directDeposit": "Direct deposit is : ",
"life.reliable": "reliable - no risk of lost, forgotten or stolen cheques or postal delays",
"life.completelyConfidential": "completely confidential",
"life.informative": "informative - your deposit notification and explanation of benefits statement are mailed immedeately upon payment",
"life.familiar": "familiar - many employees receive their salaries by direct deposit",
"life.convenient": "convenient - no need to spend valuable time depositing benefit payments at a financial institution",
"life.instructions": "Instructions",
"life.completeFieldsTransit": "Please complete fields transit, institution and account number as indicated on your cheque by omitting spaces and special characters.",
"life.note": "Note",
"life.adviceFinancialInstitution": "Please be advised that the financial institution address is updated monthly. Therefore in the event that the address changed within the last month the information might not be available or updated yet.",
"life.authorization": "Authorization",
"life.authorize": "By completing this section, I authorize insurance company to credit all my benefit payments to the mentioned account. I certify that the information provided on this authorization is accurate, and I agree to keep it up to date. I accept that this agreement may be cancelled at any time by either insurance company or myself, in writing or verbally.",

"microsite.title" : "Welcome to the ?1 microsite",
"microsite.home" : "Home",
"microsite.open.enrolment.available" : "There is an <b>open enrolment</b> currently available",
"microsite.no.open.enrolment.available" : "", //"There is no open enrolment currently available.",
"microsite.from" : "from",
"microsite.From" : "From",
"microsite.to" : "to",
"microsite.enrolment.submitted" : "<b>Your enrolment is already submitted.</b>",
"microsite.contact.administrator" : "If you need to modify your enrolment, please contact your plan administrator.",
"microsite.choose.your.coverage" : "Choose your group insurance coverage.",
"microsite.no.completed.enrolments" : "You have no completed enrolments.",
"microsite.view" : "View",
"microsite.update" : "Update",
"microsite.viewUpdate" : "View and update",
"microsite.my.life.events" : "My life events",
"microsite.my.coverage" : "My coverage",
"microsite.my.activities" : "My activities",
"microsite.my.profile" : "My profile",
"microsite.my.dependents" : "My dependents",
"microsite.add.remove.dependents" : "Update your dependents information and choose your benefits according to your life event.",
"microsite.learn.about.selections" : "View your current and past benefit selctions.",
"microsite.learn.about.history" : "View your current and past benefit selections.",
"microsite.view.profile.information" : "View and update your personal information, including your home address, smoker status and banking information.",
"microsite.view.dependents.information" : "View and update your dependents information, including your children’s student status and your spouse’s smoker status.",
"microsite.coverage.effective": "Effective date of coverage ",
"microsite.employment.info": "Employment information",
"microsite.direct.deposit.info": "Direct deposit",
"microsite.security": "Security",
"microsite.edit.personal.information": "Edit personal information",
"microsite.dependents.note.text1" : "To add/remove a dependent or to modify your spouse's insurer information, go to the <a href='#home/life-events'>My life events</a> section and follow the instructions.",
"microsite.dependents.note.text2" : "To modify your beneficiaries, please complete and sign the ",
"microsite.dependents.note.text3" : "Beneficiary designation",
"microsite.dependents.note.text4" : " form and return it to your plan administrator.",

"life-events.contact.admin": "My life events",
"life-events.info": "Update your dependents information and choose your benefits according to your life event.",
"life-events.definition": "Definition",
"life-events.matrimonialChange": "Matrimonial change",
"life-events.matrimonialChange.details": "(marriage, common-law spouse, divorce, widow, etc.)",
"life-events.additionDependentChild": "Addition of a dependent child",
"life-events.additionDependentChild.details": "(newborn, adoption, etc.)",
"life-events.removalDependentChild": "Removal of a dependent",
"life-events.removalDependentChild.details": "(child no longer eligible, etc.)",
"life-events.spouseModification": "Spouse coverage modification with another carrier",
"life-events.spouseModification.details": "(spouse no longer covered by another carrier, etc.)",
"life-events.note": "Note",
"life-events.guideline": "text box open (at plan setup) to give guidelines to the employee",
"life-events.effectiveDate": "Life event effective date",
"emplifeevents.lifeevent.note": "<p>You must declare your life events within ?1 ?2 of their effective date. Once you have entered the information requested above, you will have ?3 ?4 to review your coverage and make the necessary changes.</p><p>Depending on your life event, you may want to change the beneficiaries you have designated. To do so, please complete and sign the ?5 form and return it to your plan administrator.</p><p>Contact your plan administrator for any questions regarding eligible life events and changes to your coverage.</p>",
"emplifeevents.lifeevent.added.note":"<p>You will have ?1 ?2 to review your coverage and make the necessary changes.</p><p>Depending on your life event, you may want to change the beneficiaries you have designated. To do so, please complete and sign the ?3 form and return it to your plan administrator.</p><p>Contact your plan administrator for any questions regarding eligible life events and changes to your coverage.</p>",
"emplifeevents.lifeevent.notezerograce": "",	// leave it empty for now and take following out: <p>Your life event must be approved by your plan administrator.</p><p>Depending on your life event, you may want to change the beneficiaries you have designated. To do so, please complete and sign the ?1 form and return it to your plan administrator.</p><p>Contact your plan administrator for any questions regarding eligible life events and changes to your coverage.</p>

"emplifeevents.lifeevent.note.nobeneficiary": "<p>You must declare your life events within ?1 ?2 of their effective date. Once you have entered the information requested above, you will have ?3 ?4 to review your coverage and make the necessary changes.</p><p>Depending on your life event, you may want to change the beneficiaries you have designated. To do so, please complete and sign the beneficiary form and return it to your plan administrator.</p><p>Contact your plan administrator for any questions regarding eligible life events and changes to your coverage.</p>",
"emplifeevents.lifeevent.added.note.nobeneficiary":"<p>You will have ?1 ?2 to review your coverage and make the necessary changes.</p><p>Depending on your life event, you may want to change the beneficiaries you have designated. To do so, please complete and sign the beneficiary form and return it to your plan administrator.</p><p>Contact your plan administrator for any questions regarding eligible life events and changes to your coverage.</p>",
"emplifeevents.lifeevent.notezerograce.nobeneficiary": "",

"emplifeevents.beneficiaryDesignation": "Beneficiary designation",
"life-events.note.detail3": "For beneficiary modification, print the ",
"life-events.note.detail4": "Beneficiary designation ",
"life-events.note.detail5": "form, complete, sign and return it to plan administrator.",
"life-events.definition.text": "A major event that changes a person's status or circumstances, such as giving birth, adoption, marriage, divorce, death of spouse, death of dependent child, etc. When such event occurs, you are allowed to modify your coverage outside the official re-enrolment periods.",
"life-events.summary.current.waiting.approval": "Waiting for approval",
"life-events.summary.current.approved": "Approved",
"life-events.enrolment.open": "Enrolment period open: ",
"life-events.enrolment.period": "?1 to ?2",
"emplifeevents.lifeevent.period.day": "day(s)",
"emplifeevents.lifeevent.period.week": "week(s)",
"emplifeevents.lifeevent.period.month": "month(s)",
"life-events.inProgress": "Life event in progress",
"life-events.eventDescription": "Event description: ",
"life-events.requestDate": "Request date: ",
"life-events.effectiveDate2": "Effective date: ",
"life-events.submissionDate": "Submission date: ",
"life-events.status": "Status: ",
"life-events.warning": "Warning",
"life-events.warning1": "There is an enrolment period currently in progress. The life event section will be available when the current enrolment is completed.",
"life-events.warning2": "If you need to proceed with your life event, please contact your plan administrator.",
"life-events.warning3": "Please contact your plan administrator for any questions regarding life events or changes to your coverage.",
"life-events.warning4": "You have requested a change that requires approval from your plan administrator. Once approved, you may proceed with your life event request.",
"life-events.next": "Next",
"life-events.choose": "Choose your life event",
"life-events.confirmationSecurity": "Do you want to update your security questions?",
"life-events.confirmationBanking": "Do you want to update your banking information?",
"life-events.myDependents.text": "<p>Update your dependents information and choose your benefits according to your life event.</p><p>All modifications will be effective as of the life event effective date.</p>",
"life-events.event.effective": "Effective date ",
"emplifeevents.lifeevent.compare.text": "You may <b>keep your current</b> selections or <b>modify</b> them.",
"emplifeevents.lifeevent.compare.note": "You have until the end of the enrolment period ?1 to submit your Life event. Otherwise, your current selections will be reconducted at the end of the enrolment period.",
"emplifeevents.lifeevent.compare.view": "View my current selections",
"emplifeevents.lifeevent.compare.keep.selections.description": "This action will submit your life event",
"emplifeevents.lifeevent.compare.modify.selections.description": "This action will open My benefits for modification",
"required.fieldsInvalidDateErrorText": "Birth date can not be greater than / succeed life event effective date. Please, complete this life event and add a new life event for this dependent or, contact plan administrator",
"emplifeevents.lifeevent.zerograceperiods.contactplanadmin": "Please contact your plan administrator to complete your life event.",
"emplifeevents.addlifeevent.currenrollnotauthorized": "Contact your plan administrator for any changes to your coverage.",

"header.planWorkbook.description": "Summary of your flexible benefit plan provided by your policyholder",
"enrollNow.personal.groupInsuranceBooklet.description": "Complete information about your Group insurance plan",
"header.glossary.description": "Group insurance terminology process",
"header.tutorial.description": "Online tutorials help you with transaction to perform",
"header.beneficiary.designation.form": "Beneficiary designation form",
"last.pdf": " (PDF)",
"available.forms": "Available Forms",
"benefit.information.change": "Coordination of benefit information can only be changed under My life event menu.",
"life_events.nofuturedate":"Please do not enter future dates as an effective date for your life event",
"life-events.enrollment.ended": "Your enrollment period has ended, please contact your plan administrator.",
"life-events.summary.current.not.completed": "In progress",

"life_events.predateLifeEvent":"The date you have entered predates previously completed life event.",

//Tutorials Page
"choose_coverage":"How to choose your coverage",
"renew_coverage":"How to renew your coverage",
"change_personal_info":"How to change your personal information (address, email)",
"change_smoking_status":"How to change your smoking status",
"change_deposit_information":"How to change your direct deposit information",
"change_your_password":"How to change your password",
"view_dependent_information":"How to view your dependent information",
"view_benefit_summary":"How to view your Benefit summary",

"password_common_error": "Entered password does not comply with password complexity rules, see below",
"password_space_error": "Please do not enter spaces",
"password_mirror_error": "Password cannot be same as username",
"same_password_error": "New password cannot be same as your old password",
"coverage_page_warning": "Your current coverage will be available once you have completed your life event.",
"coverage_page_warning_incomplete": "Your current coverage will be available once it is completed.",
"dependent_screen_text": "Please ensure your dependent information is accurate prior to clicking save",

"perform_life_event": "How to perform a life event",

"call_us_now": "Call us now",
"email_us": "Email us",
"employee_login": "Employee Login",


//Registeration Page
"empregister": "Register",
"empregister.already.registered": "You have already registered, please log into your account",
"empregister.employee.notfound": "Your account was not found, please contact your plan administrator",
"empregister.missing.requiredfield": "This field is required",
"empregister.invalid.email": "Please enter a valid email address",
"empregister.invalid.birthdate": "Please enter a proper date in mm/dd/yyyy",
"empregister.firstname": "First Name",
"empregister.lastname": "Last Name",
"empregister.email.address": "Email",
"empregister.postalcode": "Postal Code",
"empregister.dateofbirth": "Date of Birth",
"empregister.username": "User Name",
"empregister.expired":"Your activation period is expired. Please, contact your plan administrator for further assistance",
"empregister.invalid.birthdaterange":"Please check the date field.",

//Scenario Comparison Page
"scenario.comparison":"Comparison",
"scenario.overview":"Overview",
"scenario.benefits":"Benefits",
"scenario.legend":"LEGEND",
"scenario.unapproved.cost":"Unapproved cost",
"scenario.unapproved.coverage":"Unapproved coverage",
"scenario.confirm": "By choosing this scenario, all other scenarios will be deleted",

"login.usernamemail.nomatch": "User ID and email do not match. Please, re-enter or contact your plan administrator.",
"select.scenario": "SELECT SCENARIO",
"add.scenario": "ADD SCENARIO",
"edit.scenario": "EDIT SCENARIO",
"forgotpassword.nosecurityquestions":"Password reset link has been sent to your email.",
"empresQs":"Please Revalidate details below. ",
"empreset.incorrectform":"Please recheck the details submitted.",
"login.usernamemail.noquestionset":"Please contact your plan administrator.",
"security.answer.maxlength":"Answer can not exceed 200 characters."

//////////////////////////////////
// Do not edit below this line  //
//////////////////////////////////
};
return exports;
});
