define([],function(){
var exports = {
//////////////////////////////////
// Enter each key value pair as //
// "key" : "value" ,            //
//////////////////////////////////
// Do not edit above this line  //
//////////////////////////////////
"unspecified": "Non précisé",
"yes": "Oui",
"no": "Non",
"error.notify": "Une erreur s’est produite. Veuillez communiquer avec l'administrateur de votre régime.",
"error.application": "Erreur: 500",

"english": "Anglais",
"french": "Français",

"m": "Homme",
"f": "Femme",

"smoker": "fumeur",
"non-smoker": "non-fumeur",

"spouse": "Conjoint",
"child": "Enfant",
"other": "Autre",
"title.enrolment": "",  // "Inscription"
"title.reenrolment": "",  // "Réinscription"
"title.lifeEvents": "",  // "Événements de ma vie"

"select": "Sélectionner",
"download": "Télécharger",
"start": "Démarrer",
"default": "(Défaut)",
"loading": "Chargement",
"administrator": "Administrateur",
"mm.dd.yyyy": "mm/jj/aaaa",
"save.changes": "Sauvegarder les modifications?",

"Optional": "Facultatif",

"Alberta": "Alberta",
"British_Columbia": "Colombie-Britannique",
"Manitoba": "Manitoba",
"New_Brunswick": "Nouveau-Brunswick",
"Newfoundland_and_Labrador": "Terre-Neuve-et-Labrador",
"Northwest_Territories": "Territoires du Nord-Ouest",
"Nova_Scotia": "Nouvelle-Écosse",
"Nunavut": "Nunavut",
"Ontario": "Ontario",
"Prince_Edward_Island": "Île-du-Prince-Édouard",
"Quebec": "Québec",
"Saskatchewan": "Saskatchewan",
"Yukon": "Yukon",

"required.fields": "Champs obligatoires",
"required.fields.asterisk": "Champs obligatoires",
"required.field": "Champs obligatoires",
"required.fieldsErrorText": "Ce champ est obligatoire.",
"required.valid.date": "La date doit être valide et indiquée selon le format suivant : mm/jj/aaaa",
"required.valid.number": "Veuillez inscrire un nombre",

"hello":"Hello world!",
"copyright":"&copy; 2013 Standard Life",

"footer.copyright": "Copyright 2014 Jardine Lloyd Thompson Group plc.",
"footer.contactUs": "Nous joindre",
"footer.support": "Soutien",
"footer.supportAndDocumentation": "Soutien et documentation",
"footer.legalInformation": "Informations juridiques",
"footer.termsOfUsage": "Conditions d’utilisation",
"footer.privacyStatement": "Confidentialité",
"footer.powered": "Powered",
"footer.by": " by",
"footer.accessibility": "Accessibilité",
"footer.privacy": "Confidentialité",
"footer.termsOfUse": "Conditions d’utilisation",

"contact.us.flexible.benefits.program": "Questions pour votre <b>'régime d’assurances flexible'</b>",
"contact.us.flexible.benefits.program.phone": "514-787-2088 ou 1-877-599-FLEX (3539)",
"contact.us.flexible.benefits.program.email": "Adresse courriel : flex@manulife.com",
"contact.us.claims": "Questions au niveau des <b>'réclamations'</b>",
"contact.us.claims.phone": "514-841-5312 ou 1-800-499-4425",
"contact.us.claims.email": "Adresse courriel : group.medent@manulife.com",

"welcome.greeting": "Renseignements d'ouverture de session",
"welcome.enroll": "Votre régime. Votre choix.",	
"welcome.enrollAndSelect": "Inscrivez-vous et faites vos choix de protections en quelques étapes simples.",
"welcome.enrollText1": "", // "Votre régime flexible d'assurances collectives est un élément important de votre rémunération globale et vous procure une protection essentielle, à vous et aux membres de votre famille."
"welcome.enrollText2": "In placerat tempus felis, vitae interdum enim laoreet nec. Donec pharetra risus eu justo vulputate pretium.",
"welcome.enrollNow": "Choisissez maintenant",
"welcome.reEnroll": "Votre régime. Votre parcours.", //"Il est temps de renouveler votre inscription.",
"welcome.reEnroll.available.from": "Du ",
"welcome.reEnroll.available.to": "au ",
"welcome.reEnroll.available.end": " c’est à vous de choisir.",
"welcome.reEnrollText1": "", // "Votre régime flexible d'assurances collectives est un élément important de votre rémunération globale et vous procure une protection essentielle, à vous et aux membres de votre famille."
"welcome.reEnrollText2": "In placerat tempus felis, vitae interdum enim laoreet nec. Donec pharetra risus eu justo vulputate pretium.",
"welcome.reEnroll.review": "Choisissez maintenant ",

"calendar.monday": "Lundi",
"calendar.thursday": "Mercredi",
"calendar.wednesday": "Jeudi",
"calendar.tuesday": "Vendredi",
"calendar.friday": "Samedi",
"calendar.saturday": "Dimanche",
"calendar.sunday": "Mardi",

"calendar.january": "Janvier",
"calendar.february": "Février",
"calendar.march": "Mars",
"calendar.april": "Avril",
"calendar.may": "Mai",
"calendar.june": "Juin",
"calendar.july": "Juillet",
"calendar.august": "Août",
"calendar.september": "Septembre",
"calendar.october": "Octobre",
"calendar.november": "Novembre",
"calendar.december": "Décembre",

"calendar.clearDate": "Effacer la date",
"calendar.today": "Aujourd'hui",

"header.supportDocumentation": "Soutien et documentation",
"header.about": "à€ propos de",
"header.legal": "Avis juridique",
"header.logout": "Déconnexion",
"header.contact": "Nous joindre",
"header.tutorial": "Tutoriel",
"header.planWorkbook": "Guide du régime",
"header.glossary": "Glossaire",
"header.faq": "Foire aux questions",

"login": "Connexion",
"login.username": "Nom d’utilisateur",
"login.password": "Mot de passe",
"login.forget.username": "Nom d’utilisateur oublié",
"login.forget.password": "Mot de passe oublié",
"login.rules.rule1": "Doit comprendre au moins ?1 caractères.",
"login.rules.rule2": "Doit contenir des lettres, des chiffres et au moins un des symboles suivants: ~!@##$%^&*",
"login.rules.rule3": "Ne doit pas être identique à votre code d'utilisateur.",
"login.questions.wrongcredentials": "Vous n’avez pas répondu correctement aux questions, veuillez contacter votre administrateur de régime afin de compléter votre demande.",
"login.questions.invalid": "Vous n’avez pas répondu correctement aux questions, veuillez contacter votre administrateur de régime afin de compléter votre demande.",
"login.error.wrong.passwdusrname": "Nom d’utilisateur erroné / mot de passe erroné",
"login.error.locked.numofloginlimit": "L’accès au système n’est plus permis car vous avez entré ?1 mots de passe invalides. Veuillez contacter votre gestionnaire de régime pour déverrouiller votre dossier.",

"change.password": "Le changement de mot de passe",
"change.my.password": "Modifier mon mot de passe",
"change.password.new.password": "Nouveau mot de passe : ",
"change.password.re.new.password": "Confirmez votre nouveau mot de passeÂ  : ",
"renewpassword.passwdhistory": "Vous ne devez pas utiliser l’un de vos 10 derniers mot de passe",
"renewpassword.passwdnosession": "Session expirée",
"renewpassword.passwdnousernamemirror": "Votre nouveau mot de passe ne peut pas être identique à votre nom d’utilisateur",
"renewpassword.passwdminlength": "Votre nouveau mot de passe doit contenir au moins 8 caractères",
"renewpassword.passwdchanged": "The password was changed (fr)",
"renewpassword.passwdwrongoldpassword": "mot de passe erroné",
"password.enterYourCurrentPassword": "Entrez votre mot de passe actuel : ",
"password.enterYourNewPassword": "Entrez votre nouveau mot de passe : ",
"password.reEnterYourNewPassword": "Confirmez votre nouveau mot de passe : ",

"forgotten.username.greeting": "Nom d’utilisateur oublié",
"forgotten.username.firstname": "Prénom",
"forgotten.username.lastname": "Nom",
"forgotten.username.birthday": "Date de naissance",
"forgotten.username.email": "Courriel",
"forgotten.username.successMsg": "Un courriel contenant votre nom d'utilisateur vous a été envoyé.",
"forgotten.username.dateValidationMsg": "Le format de date est le suivant : mm/jj/aaaa",

"forgotten.password.greeting": "Mot de passe oublié",
"forgotten.password.username": "Nom d’utilisateur",
"forgotten.password.email": "Courriel",
"forgotten.password.security.questions.header": "Veuillez répondre aux questions de sécurité suivantes puis cliquer sur transmettre",
"forgotten.password.tempLogin.notification.tempPass": "Veuillez noter et conserver votre nouveau mot de passe temporaire à portée de la main. ",
"forgotten.password.tempLogin.notification.requiredAction": "Vous devrez entrer ultérieurement votre mot de passe temporaire afin de modifier votre mot de passe après avoir ouvert une session.",
"forgotten.password.tempLogin.notification.login": "Ouvrez une session ci-dessous.",
"forgotten.password.renew.header": "S'il vous plàît renouveler votre mot de passe.",
"forgotten.password.renew": "Entrez votre nouveau mot de passe.",
"forgotten.password.tempPassword": "Mot de passe temporaire",
"forgotten.password.new.password": "Nouveau mot de passe",
"forgotten.password.confirm.new.password": "Confirmez votre nouveau mot de passe.",
"forgotten.password.wrong.temp.password": "Mot de passe temporaire erroné",

"forgotten.credentials.backtologin": "Retour à la page d'ouverture de session",
"forgotten.credentials.errorMsg": "Une information manquante à votre dossier nous empêche de traiter votre demande. Veuillez vérifiez de quoi il s'agit auprès de votre administrateur de régime. ",

"uname.recover.message": "Une information manquante à votre dossier nous empêche de traiter votre demande. Veuillez vérifiez de quoi il s'agit auprès de votre administrateur de régime. ",

"date.format": "mm/jj/aaaa",
"cancel":"Annuler",
"continue": "Continuer",
"back": "Précédent",
"save": "Sauvegarder",
"reset": "Réinitialiser",
"save.continue": "Sauvegarder et continuer",
"edit": "Modifier",
"details": "Détails",
"notes": "Remarques",
"submit": "Soumettre",
"none": "Aucun",
"home": "Accueil",
"submit.enrolment": "Transmettre l’inscription",
"submit.lifeEvent": "Transmettre l’événement de la vie",

"change.password.header": "S'il vous plàît mettre à jour votre profil", 
"change.password.error.not.matching": "Vos mots de passe ne sont pas identiques.",
"change.password.error.not.valid": "Les mots de passe devraient contenir au moins un chiffre et un caractère.",
"change.password.rules": "Votre nouveau mot de passe",

"security.questions": "Questions de sécurité",
"security.questions.question.1": "Quelle était la marque de votre première voiture?",		
"security.questions.question.2": "Quel était le nom de l'école primaire que vous avez fréquentée?",		
"security.questions.question.3": "Quel est le nom de jeune fille de votre mère?",		
"security.questions.question.4": "Quel est votre dessert favori?",		
"security.questions.question.5": "Quel est votre animal préféré?",		
"security.questions.question.6": "Quelle destination aimeriez-vous visiter?",		
"security.questions.question.7": "Quel était le nom votre premier employeur?",		
"security.questions.question.8": "Quel était le nom de votre premier amour?",		
"security.questions.question.9": "Quel est le nom de votre acteur/actrice préféré?",		
"security.questions.question.10": "Quel est le titre de votre film favori?",		
"security.questions.question.11": "Quel sport pratiquez-vous ou aimeriez-vous pratiquer?",		
"security.questions.question.12": "Quelle est votre couleur préférée?",
"security.questions.error.unique": "Veuillez choisir une autre question",

"enrollNow.personal.info": "Renseignements personnels",
"enrollNow.my.profile": "Mon profil",
"enrollNow.dependents": "Mes personnes à charge",
"enrollNow.personal.verifyText": "Vérifiez l'exactitude de vos renseignements. En cas d'erreur, communiquez avec votre représentant des ressources humaines avant de transmettre.",
"enrollNow.benefits": "Mes garanties",

"enrollNow.costs": "Mon sommaire",
"enrollNow.personal.zipPostalCodeNote": "Sans espace ni tiret entre les caractères (ex. : A1A1A1)",
"enrollNow.personal.charactersLimit": "Maximum de 50 caractères par ligne",

"congratulations": "Félicitations",
"congratulations.text1": "Félicitations !",
"congratulations.text2": "Votre demande d'inscription a été <strong>transmise</strong>",
"congratulations.lifeEvent.text2": "Votre événement de vie a été <strong>transmis</strong>",
"congratulations.text4": "Lorsqu'elle aura été approuvée, vous recevrez un courriel de confirmation qui vous indiquera, entre autres, la date d'entrée en vigueur de votre couverture et les mesures que vous devrez prendre.",
//"congratulations.lifeEvent.text4": "",	// Lorsqu'elle aura été approuvée, vous recevrez un courriel de confirmation qui vous indiquera, entre autres, la date d'entrée en vigueur de votre couverture et les mesures que vous devrez prendre.
"congratulations.text5": "Si vous avez besoin de modifier vos choix, veuillez communiquer avec l'administrateur de votre régime.",
"congratulations.benefit.summary.form": "Vous pouvez imprimer le présent sommaire des garanties pour vos dossiers.",
"congratulations.benefit.summary.available": " Vous pouvez aussi le consulter sous Mes protections > Sommaire des garanties.",
"congratulations.beneficiary.designation.form": "Formulaire de désignation de bénéficiaire",
"congratulations.evidence.insurability.form": "Formulaire preuves d'assurabilité",
"congratulations.critical.illness.form": "Preuves d'assurabilité pour l'assurance maladies graves",
"congratulations.RRSP.form": "Formulaire d'inscription au régime enregistré d'épargne-retraite (REER) collectif",
"congratulations.benefit.summary.PDF": "Sommaire des garanties (PDF)",
"congratulations.benefits.designation.PDF": "Formulaire de désignation de bénéficiaire (PDF)",
"congratulations.evidence.insurability.PDF": "Formulaire preuves d'assurabilité (PDF)",
"congratulations.critical.illness.PDF": "Preuves d'assurabilité pour l'assurance maladies graves (PDF)",
"congratulations.RRSP.PDF": "REER (PDF)",
"congratulations.print.form": "Imprimer le formulaire",
"congratulations.send.to.email": "Envoyer le formulaire par courriel",
"congratulations.download.summary": "Télécharger mon sommaire",
"congratulations.download.form": "Télécharger le formulaire",
"congratulations.benefits.summary.PDF": "Sommaire des garanties (PDF)",
"congratulations.benefits.summary.temporary": "Sommaire des garanties (temporaire)",
"congratulations.actions.required.header": "Prochaines étapes",
"congratulations.actions.required.text": "En fonction de vos choix, vous devez prendre certaines mesures :",
"congratulations.actions.email.subject.beneficiary": "Formulaire de désignation de bénéficiaire",
"congratulations.actions.email.subject.evidence": "Formulaire preuves d'assurabilité",
"congratulations.actions.email.subject.rsp": "REER",
"congratulations.actions.email.send.success": "Courriel transmis avec succès",
"congratulations.actions.email.send.failure": "Erreur lors de l'envoi du courriel",
"congratulations.beneficiary.designation.form.description": "Vous devez remplir et signer le formulaire Désignation de bénéficiaire et le retourner à votre administrateur de régime.",
"congratulations.enroll.beneficiary.designation.form.description": "Vous devez remplir, signer et faire parvenir le formulaire au service des ressources humaines de votre division, à défaut de quoi, les bénéficiaires inscrits à votre dossier seront vos héritiers légaux.",
"congratulations.reEnroll.beneficiary.designation.form.description": "Pour modifier vos bénéficiaires, il vous suffit de remplir et signer le formulaire Désignation de bénéficiaire et de le retourner à votre administrateur de régime.",
"congratulations.formsAreAvailable": "Ces formulaires sont aussi accessibles sous Documentation > Formulaires",
"congratulations.actions.email.invalid": "Cannot email form, the email address for your account is improperly configured (fr)",

"coverage.my.coverage": "Mes protections",
"coverage.unused.credits": "Crédits inutilisés",
"coverage.unallocated.credits": "Crédits non affectés (solde)",
"coverage.enrolment.summary": "Sommaire de l'inscription",
"coverage.lifeEvent.summary": "Sommaire de l’événement de la vie",
"coverage.life-events.summary": "Mes protections",
"coverage.life-events.effective_date": "Date d'effet de vos protections",
"coverage.life-events.coverage_status": "Statut de vos protections",
"coverage.please.validate": "Veuillez valider tous les renseignements et vos choix et transmettre votre inscription",
"coverage.lifeEvent.please.validate": "Veuillez valider tous les renseignements et vos choix et transmettre votre événement de la vie",
"coverage.my.history": "Mon historique",
"coverage.your.benefit.coverage": "Protections actuelles",
"coverage.your.benefit.history": "Transactions",
"coverage.benefit.description": "Description/garanties",
"coverage.option": "Option",
"coverage.coverage": "Couverture",
"coverage.benefit.cost": "Coût des garanties",
"coverage.employer.share": "Part de l'employeur",
"coverage.my.share": "Ma part",
"coverage.flex.credits": "Crédits flexibles",
"coverage.payroll.deduction": "Retenues salariales",
"coverage.life.ADD.insurane": "Life and AD&D Insurance",
"coverage.unapproved.amount": "(montants non approuvés)",
"coverage.dependent.life.insuranec": "Dependent life insurance",
"coverage.optional.life.insurance": "Optional life insurance",
"coverage.spouse.optional.life.insurance": "Spouse optional life insurance",
"coverage.children.optional.life.insurance": "Children optional life insurance",
"coverage.optional.ADD.insurance": "Optional AD&D insurance",
"coverage.spouse.optional.ADD.insurance": "Spouse optional AD&D insurance",
"coverage.children.optional.ADD.insurance": "Children optional AD&D insurance",
"coverage.short.term.disability": "Short term disability",
"coverage.long.term.disability": "Long term disability",
"coverage.health.insurance": "Health insurance",
"coverage.dental.care": "Dental care",
"coverage.optional.critical.illness": "Optional critical illness (1)",
"coverage.employee.optional.critical.illness": "Employee optional critical illness (1)",
"coverage.spouse.optional.critical.illness": "Spouse optional critical illness (2)",
"coverage.total.cost": "Coàts totaux",
"coverage.total.cost.unapproved.amounts": "Coàt total comprenant les montants non approuvés",
"coverage.monthly.cost.summary": "Sommaire de mes coàts mensuels",
"coverage.flexible.credits": "Crédits flexibles disponibles",
"coverage.flex.credits.used": "Crédits flexibles utilisés",
"coverage.group.benefit.plan.cost": "Coût du régime d'assurances collectives",
"coverage.balance.payroll.deduction": "Solde (+) / retenues salariales (-)",
"coverage.cost.for.payroll.deduction": "Coût des garanties payées par retenues salariales",
"coverage.cost.by.payroll.deduction": "Coàts payés par retenues salariales (y compris les montants non approuvés)",
"coverage.total.cost.excluding.retail": "Coàts totaux payés par retenues salariales (sans les taxes applicables)",
"coverage.total.cost.including.retail": "Coàts totaux payés par retenues salariales, incluant les montants non approuvés (sans les taxes applicables)",
"coverage.unused.flex.credits.distribution": "Affectation de mes crédits flexibles inutilisés",
"coverage.balance.flex.credits": "Solde des crédits flexibles",
"coverage.cash": "Encaissement",
"coverage.health.spending.account": "Compte de frais médicaux (CFM)",
"coverage.group.registered.savings": "Régime enregistré d'épargne-retraite collectif (REER)",
"coverage.registered.pension.plan": "Régime de pension agréé (RPA)",
"coverage.group.tax.free": "Compte d'épargne libre d'impôt collectif (CELI)",
"coverage.total.employer.contribution": "Cotisation totale de l’employeur",
"coverage.total.employer.contribution.plan": "Cotisation totale de l’employeur à votre régime d’assurances",
"coverage.taxable.benefits.provincial": "Avantages imposables (provincial)",
"coverage.taxable.benefits.federal": "Avantages imposables (fédéral)",
"coverage.life.event": "Événement de la vie",
"coverage.enrolment": "Inscription",
"coverage.initial.enrolment": "Inscription initiale",
"coverage.enrolment.type": "Types de transactions",
"coverage.effective.date.coverage": "Date d'effet",
"coverage.enrolment.period": "Période d'inscription",
"coverage.authorized.on": "Autorisé le",
"coverage.authorized.by": "Autorisé par",
"coverage.benefit.summary.conf.stat": "Sommaire des protections",

"coverage.your.benefit.coverage.comparison": "Comparaison de protections",
"coverage.monthly.cost.comparison": "Sommaire de mes coàts mensuels",
"coverage.unused.flex.credits.distribution.comparison": "Affectation de mes crédits flexibles inutilisés",
"coverage.comparison.current.period": "Période actuelle",
"coverage.comparison.new.period": "Nouvelle période",
"coverage.current.coverage": "Protections actuelles",
"coverage.coverage.history": "Historique de mes protections",

"enrollNow.unusedCredits": "Mes crédits",
"benefits.mySelections": "Mes garanties",
"enrollNow.personal.birthday": "Date de naissance : ",
"enrollNow.personal.gender": "Sexe : ",
"enrollNow.personal.languagePreference": "Langue de correspondance : ",
"enrollNow.personal.effectiveDate": "Date d’effet : ",
"enrollNow.personal.zip.postal.code": "Code postal : ",
"enrollNow.personal.sin": "SIN : ",
"enrollNow.personal.hireDate": "Date d'embauche : ",
"enrollNow.personal.class": "Nom de la catégorie : ",
"enrollNow.personal.certificateNumber": "Numéro de certificat : ",
"enrollNow.personal.planAdministrator": "Administrateur du régime : ",
"enrollNow.personal.position": "Position : ",
"enrollNow.personal.langPreference": "Langue de correspondance : ",
"enrollNow.personal.ruSmoker": "Fumez-vous? ",
"enrollNow.personal.division": "Nom du compte : ",
"enrollNow.personal.address": "Adresse",
"enrollNow.personal.street": "Rue : ",
"enrollNow.personal.aptUnit": "App./unité : ",
"enrollNow.personal.city": "Ville : ",
"enrollNow.personal.zipPostalCode": "Code postal : ",
"enrollNow.personal.stateProvince": "État/province : ",
"enrollNow.personal.stateProvinceChange": "Si vous avez changé de province de résidence, entrez la date d'effet du changement. ",
"enrollNow.personal.phoneInfo": "Numéros de téléphone et courriel",
"enrollNow.personal.smokingStatus": "Statut fumeur",
"enrollNow.personal.nonSmokerDefinition": "Définition d’un non-fumeur",
"enrollNow.personal.haveNotSmoked.text1": "Définition d’un non-fumeur: N’avoir fumé ni cigarette ni petit cigare au cours des 12 mois qui précèdent la date de signature de la demande de participation. ",
"enrollNow.personal.haveNotSmoked.text2": "Pour une définition complète, veuillez consulter votre",
"enrollNow.personal.groupInsuranceBooklet": "Livret d'assurances collectives",
"enrollNow.personal.currentSmokerStatus": "Votre statut fumeur est : ",
"enrollNow.personal.lastEffectiveDate": "Dernière date d'effet : ",
"enrollNow.personal.newSmokerStatus": "Nouveau statut fumeur : ",
"enrollNow.personal.newEffectiveDate": "Nouvelle date d'effet : ",
"enrollNow.personal.smokingStatusText": "Veuillez préciser si vous êtes fumeur ou non-fumeur. Pour être considéré non-fumeur, vous ne devez pas avoir fait usage de produits du tabac au cours des douze mois précédent votre inscription.",
"enrollNow.personal.homePhoneNum": "Numéro de téléphone à la maison : ",
"enrollNow.personal.cellPhoneNum": "Numéro de téléphone cellulaire : ",
"enrollNow.personal.emergContactName": "Nom de la personne à joindre en cas d'urgence : ",
"enrollNow.personal.emergContactNumber": "Numéro à joindre en cas d'urgence : ",
"enrollNow.personal.email": "Courriel : ",
"enrollNow.personal.busPhoneNumber": "Numéro de téléphone au travail : ",
"enrollNow.personal.extension": "Poste : ",
"enrollNow.personal.employmentInfo": "Renseignements sur l'emploi",
"enrollNow.personal.policyholder": "Titulaire de police : ",
"enrollNow.personal.provinceOfEmplyment": "Province d'emploi : ",
"enrollNow.personal.policyNumber": "Numéro de police : ",
"enrollNow.personal.divisionNumber": "Numéro du compte : ",
"enrollNow.personal.classNumber": "Numéro de catégorie : ",
"enrollNow.personal.costCenter": "Centre de coàts : ",
"enrollNow.personal.username": "Nom d'utilisateur : ",
"enrollNow.personal.employeeNumber": "Numéro d'employé : ",
"enrollNow.personal.dependentStatus": "Statut des personnes à charge : ",
"enrollNow.personal.bankingInfo": "Renseignements bancaires",
"enrollNow.personal.bankAccountNumber": "Nº de compte : ",
"enrollNow.personal.institutionNumber": "Nº d'institution : ",
"enrollNow.personal.bankTransitNumber": "Nº de succursale : ",
"enrollNow.personal.viewSampleCheck": "View Sample Check",
"enrollNow.personal.directDepositText": "Je souhaite que le remboursement de mes demandes de règlement soit effectué par dépôt direct dans mon compte bancaire. ",

"enrollNow.personal.phoneNumberValidation": "Le numéro de téléphone doit être valide",
"enrollNow.personal.cellPhoneNumberValidation": "Le numéro de téléphone cellulaire doit être valide",
"enrollNow.personal.busPhoneNumberValidation": "Le numéro de téléphone au travail doit être valide",
"enrollNow.personal.busPhoneNumberExtensionValidation": "Le numéro de poste doit être valide",
"enrollNow.personal.emergNumberValidation": "Le numéro de téléphone de la personne à joindre en cas d'urgence doit être valide",
"enrollNow.personal.addressEffectiveDateValidation": "La date doit être valide et indiquée selon le format suivant : mm/jj/aaaa",
"enrollNow.personal.addressEffectiveDateValidationMoreThanEqualToday": "La date doit être ultérieure ou égale à la date d'aujourd'hui.",
"enrollNow.personal.addressEffectiveDateValidationLessThanEqualToday": "La date doit être antérieure ou égale à la date d'aujourd'hui.",

"enrollNow.personal.bankAccountNumberValidation": "Le numéro de compte ne doit contenir que des chiffres (jusqu'à 20 chiffres au maximum)",
"enrollNow.personal.institutionNumberValidation": "Le numéro d’institution ne doit contenir que des chiffres",
"enrollNow.personal.bankTransitNumberValidation": "Le numéro de succursale ne doit contenir que des chiffres (5 chiffres)",
"enrollNow.personal.emergNameValidation": "Le nom de la personne-ressource doit être valable.",
"enrollNow.personal.smokerValidation": "Vous devez préciser votre statut fumeur",

"enrollNow.personal.directDeposit.title": "Renseignements sur le dépôt direct",
"enrollNow.personal.directDeposit.5digits": "5 chiffres",
"enrollNow.personal.directDeposit.3digits": "3 chiffres",

"dependents": "Personnes à charge",
"dependents.definition": 'Indiquez les noms de vos personnes à charge et leurs renseignements personnels. Portez une attention particulière aux renseignements sur l’usage du tabac de votre conjoint. ',
"dependents.definitionTitle": "Indiquez les noms de vos personnes à charge et leurs renseignements personnels. Portez une attention particulière aux renseignements sur l’usage du tabac de votre conjoint. ",
"dependents.name": "Nom",
"dependents.type": "Lien",
"dependents.discontinueCoverage": "Terminer la couverture",
"dependents.addDependent": "Ajouter une personne à charge",
"dependents.editDependent": "Modifier",
"dependents.relationship": "Lien",
"dependents.effectiveDate": "Date d'effet",
"dependents.firstName": "Prénom",
"dependents.lastName": "Nom",
"dependents.gender": "Sexe",
"dependents.birthDate": "Date de naissance",
"dependents.ssnsin": "SSN/NAS",
"dependents.coveredElsewhere": "La personne à charge détient-elle une autre couverture?",
"dependents.noSpaces": "Aucun espace",
"dependents.discontinue.message": "àŠtes-vous certain de vouloir résilier votre couverture?",
"dependents.terminated.awaiting.approval": "Une demande de résiliation de la couverture a été transmise.",
"dependents.terminsched.awaiting.approval": "La résiliation de la couverture est prévue le",
"dependents.insurerName": "Nom de la compagnie d'assurance",
"dependents.policyNumber": "Numéro de police",
"dependents.doesMedicalCoverage": "Sont-ils couverts pour les soins de santé?",
"dependents.doesDentalCoverage": "Sont-ils couverts pour les soins dentaires?",
"dependents.atLeastOneField": "Au moins un des indicateurs d'assurance maladie ou de soins dentaires doit être réglé à oui",
"dependents.smoker": "La personne à charge Fume-t-elle?",
"dependents.smoker.notAvailable": "N/A",
"dependents.discontinue.confirm": "", // "Confirmez-vous la résiliation de la couverture?"
"dependents.no.dependent": "Aucune personne à charge n'est inscrite à votre dossier",
"dependents.cancelConfirmation": "Si vous avez saisi des données, elles ne seront pas enregistrées",
"dependents.status": "Statut",
"dependent.status.active": "Actif",
"dependent.status.pending": "En attente",
"dependent.status.awaiting_approval": "Approbation en cours",

"benefits.Selections": "Choix des garanties",
"benefits.descriptionPart1": "Pour chaque garantie, vous devez indiquer votre choix en cliquant sur le bouton à côté du nom de l'option désirée.",
"benefits.descriptionPart2": "Pour de plus amples renseignements au sujet d'une garantie, consultez votre trousse d'inscription.",
"benefits.MakeChanges": "Vos choix d'inscription actuels sont sélectionnés par défaut. Veuillez faire défiler la page vers le bas pour voir les options de garantie et faire tous les changements appropriés.",
"benefits.dentalInsurance": "Dental Insurance",
"benefits.health": "Health",
"benefits.dental": "Dental",
"benefits.life": "Life",
"benefits.disability": "Disability",
"benefits.costCalculator": "Calculateur de coàts",
"benefits.optionalBenefits": "Optional Benefits",
"benefits.optionalBenefits.participantSpouseLife": "Partisipant Spouse Life",
"benefits.optionalBenefits.participantSpouseIllness": "Partisipant Spouse Illness",
"benefits.monthlyCredits": "Crédits mensuels",
"benefits.availableCredits": "Crédits inutilisés",
"benefits.usedCredits": "Crédits utilisés",
"benefits.balancePayroll": "Solde (+) / Retenues salariales (-)",
"benefits.used": "Utilisés",
"benefits.remaining": "Inutilisés",
"benefits.employerPaidCosts": "Coûts payés par l'employeur",
"benefits.employerPaidCost": "Coûts payés par l’employeur",
"benefits.monthlyCost": "Coûts mensuels",
"benefits.benefitCost": "Coûts",
"benefits.employerShare": "Part de l'employeur",
"benefits.amount": "Montants",
"benefits.yourShareFC": "Crédits flexibles",
"benefits.yourSharePD": "Retenues salariales",
"benefits.yourSharePD.requested": "Retenues salariales avant approbation",
"benefits.yourSharePD.approved": "Retenues salariales après approbation",
"benefits.monthlyPayrollDeduction": "Retenues salariales mensuelles",
"benefits.monthlyPayrollDeductionHint": "Conseil",
"benefits.monthlyPayrollDeductionInfo": "Si vous avez choisi une couverture qui requiert une preuve d'assurabilité, votre demande de couverture sera en attente jusqu'à ce qu'elle soit approuvée mais le montant 'Après approbation' inclura le coût de la couverture demandée. Entre temps, le maximum permis sans preuve d'assurabilité sera appliqué et reflété dans le montant ' Avant approbation'.",
"benefits.beforeApproval": "Avant approbation",
"benefits.afterApproval": "Après approbation",
"benefits.PdBeforeApproval": "Retenues salariales avant approbation",
"benefits.PdAfterApproval": "Retenues salariales après approbation",
"benefits.paymentText": "Lorem ipsum dolor sit amet ctetur adipiscing elit. Donec pharetra risus eu justo vulputate pretium. Lorem ipsum dolor sit amet ctetur adipiscing elit. Donec pharetra risus eu justo vulputate pretium.",
"benefits.paymentMethod": "Mode de paiement",
"benefits.flexCredits": "Crédits flexibles",
"benefits.payrollDeduction": "Retenues salariales",
"benefits.options": "Options",
"benefits.coverage.grade": "Niveau de couverture",
"benefits.coverage": "Couverture",
"benefits.requested.coverage": "Couverture demandée",
"benefits.requested.coverage.amount": "Couverture demandée montants",
"benefits.my.coverage": "Mes protections",
"change.my.benefits": "Modifier mes garanties",
"keep.same.selection": "Conserver les mêmes sélections",
"view.coverage.history": "Voir l'historique de vos protections",
"benefits.yourShare": "Votre part",
"benefits.approved.coverage.amount": "Couverture approuvée",
"benefits.approved.coverage": "Couverture approuvée",
"benefits.approved.cost": "Coût approuvé",
"benefits.optionA": "Option A",
"benefits.optionB": "Option B",
"benefits.optionC": "Option C",
"benefits.optionOptOut": "Opt Out",
"benefits.dropdown.employee": "Employee",
"benefits.dropdown.employeePlusOne": "Employee + 1",
"benefits.dropdown.employeePlusFamily": "Employee + Family",
"benefits.option.not.selected.warning": "Veuillez sélectionner une option de garantie, puis sauvegarder et continuer.",
"benefits.coverage.not.selected.warning": "Veuillez sélectionner une couverture, puis sauvegarder et continuer.",
"benefits.option.paymentMethod.not.selected.warning": "Veuillez sélectionner un mode de paiement , puis sauvegarder et continuer.",
"benefits.option.minMaxRangeValidation": "La contribution doit être identique ou plus que le contribution maximale permise.",
"benefits.leaveConfirmation":"Toutes les données saisies sur cette page ne seront pas enregistrées. Voulez-vous continuer?",
"benefits.select.higher.option": "Afin de pouvoir sélectionner cette option, vous devez choisir l’option la plus élevée en ?1",
"benefits.credits": "Crédits flexibles",
"benefits.credits.allowed": "Crédits alloués",
"benefits.used.one": "Utilisés",
"benefits.balance": "Solde",
"benefits.employer.share": "Part de l'employeur",
"benefits.payroll.deduction": "Retenues salariales",
"benefits.payroll.deduction.before.approval": "Retenues salariales avant approbation",
"benefits.payroll.deduction.after.approval": "Retenues salariales après approbation",
"benefits.wasSelected": "Cette option a déjà été sélectionnée",

"unusedCredits.headerText": "Lorem ipsum dolor sit amet ctetur adipiscing elit. Donec pharetra risus eu justo vulputate pretium. Lorem ipsum dolor sit amet ctetur adipiscing elit. Donec pharetra risus eu justo vulputate pretium.",
"unusedCredits.flexCreditAllocation": "Attribution de crédits flexibles",
"unusedCredits.flexTitle1": "Vous disposez de ",
"unusedCredits.flexTitle2": " crédits inutilisés. Vous devez les affecter avant de transmettre votre inscription. Voici les options qui s'offrent à vous:",
"unusedCredits.retirementProgram": "Retirement Program",
"unusedCredits.healthSpendingAccountHSA": "Compte de frais médicaux (CFM)",
"unusedCredits.cash": "Encaissement",
"unusedCredits.retirementProvider": "Retirement Provider 1",
"unusedCredits.unallocatedCredits": "Le nombre de crédits non attribués doit être égal à 0 (zéro)",
"unusedCredits.numberValidationErrorText": "Entrez un nombre supérieur à 0 (zéro)",
"unusedCredits.leaveConfirmation": "Toutes les données saisies sur cette page ne seront pas enregistrées. Voulez-vous continuer?",
"unusedCredits.minCredit": "Entrez un nombre supérieur à 0 (zéro)",

"scenario.summary": "Sommaire",
"scenario.headerText1": "Before committing to your final choices, you may save up to three plan scenarios for comparison.",
"scenario.headerText2": "To edit a scenario select any of the benefit choices.",
"scenario.scenario": "Scénario",
"scenario.addScenario": "Add",
"scenario.close": "Close Scenario",
"scenario.selectedScenario": "Selected Scenario",
"scenario.available": "Disponible",
"scenario.used": "Utilisés",
"scenario.balance": "Équilibre",
"scenario.coreCoverage": "Core Coverage",
"scenario.dependentLife": "Dependent Life",
"scenario.criticalIllnesses": "Critical Illnesses",
"scenario.shortTermDisability": "Short Term Disability",
"scenario.longTermDisability": "Long Term Disability",
"scenario.employerPaidCostsMonthly": "Employer Paid Costs (Monthly)",
"scenario.payrollDeductionMonthly": "Retenues salariales mensuelles",
"scenario.scenarioSelected": "Scenario Selected",
"scenario.submitSelections": "Submit Selections",
"scenario.coverageSelection.date.range.from": "Coverage selections are from",
"scenario.coverageSelection.date.range.to": "to",
"scenario.headerText3": "Lorem ipsum dolor sit amet ctetur adipiscing elit. Donec pharetra risus eu justo vulputate pretium. In placerat tempus felis, vitae interdum enim laoreet nec. Donec pharetra risus eu justo vulputate pretium.",
"scenario.removeScenario.confirmMsg": "Are you sure you want to remove scenario",
"scenario.removing.confirm": "Confirm Removing Scenario",

"splash.welcome.BP": "Employee login",
"splash.significantLifeEvent": "Un événement important dans votre vie est-il survenu depuis la dernière fois oà¹ vous avez passé en revue ou sélectionné vos garanties flexibles?",
"splash.viewReadonlyBenefits": "Voir vos garanties",
"splash.matrimonialChange": "Changement d'état civil",
"splash.additionDependent": "Ajout d'une personne à charge",
"splash.removalDependent": "Suppression d'une personne à charge",
"splash.spouseCoverageModification": "Modification de la couverture du conjoint",
"splash.other": "Other",
"splash.matrimonialEffectifeDate": "Date d'effet du changement d'état civil",
"splash.updateMaritalStatus": "Mise à jour de l'état civil",
"splash.additionDependentChildEffectiveDate": "Date d'effet de l'ajout de la personne à charge",
"splash.addDependentChildEffectiveDate": "Date d'effet de l'ajout de la personne à charge/ Date d'effet de l'ajout del'enfant à charge",
"splash.addDependentChild": "Ajouter une personne à charge",
"splash.removeDependentChildEffectiveDate": "Date d'effet de la suppression de la personne à charge",
"splash.removeDependentChild": "Supprimer la personne à charge",
"splash.additionSpouseEffectiveDate": "Ajouter la date d'effet de la modification de la couverture du conjoint",
"splash.updateadditionSpouse": "Ajouter la modification de la couverture du conjoint",
"splash.additionOtherEffectiveDate": "Ajouter d'autres dates d'effet",
"splash.updateadditionOther": "Ajouter d'autres",
"splash.lifeEvents.maxPeriodExceeded.warning": "Max period is exceeded.",
"splash.lifeEvents.maxPeriodExceeded.error.title": "Erreur: (période maximale)",
"splash.lifeEvents.maxPeriodExceeded.error.message": "Votre événement de la vie doit être approuvé par l'administrateur de votre régime.",
"splash.lifeEvents.preCurrentCoverage.error.title": "Erreur : La date d’entrée en vigueur précède la date d’inscription.",
"splash.lifeEvents.preCurrentCoverage.error.message": "La date d’entrée en vigueur de l’événement de vie déclaré précède une date de garantie déjà établie. Veuillez communiquer avec votre administrateur de régime.",
"splash.lifeEvents.gracePeriodExceeded.warning.title": "Avertissement : Délai de grà¢ce",
"splash.lifeEvents.gracePeriodExceeded.warning.message": "L’événement de vie déclaré doit être approuvé par l'administrateur du régime.",

"healthSpendingAccountHSA": "Compte de frais médicaux (CFM)",
"cash": "Encaissement",
"retirementProvider": "Retirement Provider 1",
"unusedCredits.unallocatedCreditsYouHave": "Vous avez des crédits flexibles non attribués : ",
"unusedCredits.unallocatedCreditsOverSpent": "Vous avez surutilisé vos crédits flexibles de : ",

"coverage.history": "Historique de vos protections",
"coverage.history.plan": "Régime",
"coverage.history.plan.type": "Type",
"coverage.history.plan.last.modified": "Dernière modification",

"summary": "Sommaire des sélections relatives au régime",
"summary.definition.title.from": "Les sélections de couverture sont pour la période du ",
"summary.definition.title.to": "a",
"summary.definition": "Lorem ipsum dolor sit amet ctetur adipsiccing elit. Donec pharetra risus eu justo vulputate pretium. Lorem ipsum dolor sit amet ctetur adipsiccing elit. Donec pharetra risus eu justo vulputate pretium.",
"summary.allocated": "Monthly Flex Credits Allocated : ",
"summary.used": "Utilisés  : ",
"summary.remaining": "Restants : ",
"summary.benefit": "Garanties",
"summary.totalCost": "Coàts totaux",
"summary.flexCreditsSpent": "Crédits flexibles dépensés",
"summary.employerShare": "Employer Share",
"summary.yourShare": "Part de l'employeur",
"summary.payrollDeductions": "Retenues salariales",
"summary.payrollDeductionsAfterApproval": "Retenues salariales après approbation",
"summary.health": "Health",
"summary.dental": "Dental",
"summary.life": "Life",
"summary.disability": "Disability",
"summary.total": "Total",
"summary.yourLeftOverAllocated": "Vos crédits flexibles restants ont été attribués à : ",
"summary.RRSP": "RRSP",
"summary.HSA": "HSA",

"summary.finalizationAcceptance": "Conclusion et acceptation",
"summary.Disclaimer": "Avis de non-responsabilité",
"summary.declare.reading": "I declare to have read the text above and I accept all the terms and condition. Select the checkbox if you agree and want to submit your selections",
"summary.declare.reading.accept": "Je déclare avoir pris connaissance du texte qui précède et j'en accepte toutes les modalités.",
"summary.hereby.accept": "I hereby accept the conditions...",
"summary.confirm.message": "En cliquant sur OK, vos choix de garanties seront transmis et votre inscription sera terminée.",

"summary.reenroll": "Comparaison des protections",
"summary.reenroll.description": "Vous trouverez ci-dessous la comparaison des protections pour les deux périodes d'inscription. Pour la nouvelle période, vous pouvez conserver ou modifier vos choix actuels.",
"summary.reenroll.keep.selections": "Conserver mes choix actuels",
//"summary.reenroll.keep.selections.description": "Cette action vous dirigera vers la section Mon sommaire.",
"summary.reenroll.modify.selections": "Modifier mes choix",
//"summary.reenroll.modify.selections.description": "Cette action vous permettra de modifier vos choix.",

// global
"flex.credits": "Crédits flexibles",
"payroll.deductions": "$",
"session.sessionexpired": "Votre session a expiré, veuillez ouvrir une nouvelle session ou communiquer avec l'administrateur de votre régime",

// /login/passwd.cfc
"passwd.passwdnousernamemirror": "Votre nouveau mot de passe ne peut pas être identique à votre nom d’utilisateur",
"passwd.passwdminlength": "Votre nouveau mot de passe doit contenir au moins ?1 caractères",
"passwd.passwdcomplex": "Le mot de passe doit contenir des lettres, des chiffres et au moins un des symboles suivant ~!@##$%^&*",
"passwd.passwdhistory": "Vous ne devez pas utiliser l’un de vos 10 derniers mot de passe.",

// /login/questions.cfc
"questions.wrongcredentials": "Vous n’avez pas répondu correctement aux questions, veuillez contacter votre administrateur de régime afin de compléter votre demande.",
"questions.noquestionsfound": "Aucune question de sécurité n'a été trouvée",

// /login/sponsquestions.cfc
"sponsquestions.noquestionsfound": "Aucune question de sécurité n'a été trouvée",
"sponsquestions.errorsettingquestions": "Une information manquante à votre dossier nous empêche de poursuivre avec votre demande. Veuillez vérifier auprès de votre administrateur de régime.",

// /myinfo/dependent.cfc
"dependent.requested.birthdate.change.from{}1.to{}2": "Le statut de fumeur de votre personne à charge a été changé de 1? à 2? ",
"dependent.spousesmoker.changed.from{}1.to{}2": "L'employé demande de changer le statut de fumeur de 1? à 2?",
"dependent.requested.is_smoker.change.from{}1.to{}2": "Employee requested change of spouse smoker status from ?1 to ?2",
"dependent.add.alreadyexist": "Cette personne à charge a déjà été ajoutée",
"dependent.add.reallocatedcredits": "Les crédits flexibles alloués ont été recalculés et les sélections ont été réouvertes. Accéder à l’onglet Sélections pour effectuer vos choix.",
"dependent.awaiting.approval": "Approbation en cours",
"dependent.termindate.sched": "La résilitation de la protection de cette personne à charge aura lieu le ?1",
"dependent.smoker.sched": "Le changement de statut de fumeur aura lieu le ?1",
"dependent.termindate": "for coverage termination. (fr)",
"dependent.birthdate": "birthdate change.",
"dependent.approved.futuredate": "Your dependent will be effective ?1 (fr)",

// /myinfo/employee.cfc
"employee.passwordcomplex": "Le mot de passe doit contenir des lettres, des chiffres et au moins un des symboles suivant ~!@##$%^&*",
"employee.passwminlength": "Votre nouveau mot de passe doit contenir au moins ?1 caractères",
"employee.updatesecurityinfo.passwdempty": "Veuillez entrer votre ancien mot de passe",
"employee.updatesecurityinfo.passwdnew.dontmatch": "Ne correspond pas",
"employee.updatesecurityinfo.passwdnewempty": "Veuillez entrer votre nouveau mot de passe",
"employee.updatesecurityinfo.passwdnewshort": "Votre nouveau mot de passe doit contenir au moins ?1 caractères",
"employee.updatesecurityinfo.passwmirror": "Votre nouveau mot de passe ne peut pas être identique à votre nom d’utilisateur",
"employee.updatesecurityinfo.passwdduplicate": "Votre nouveau mot de passe ne peut pas être identique à votre ancien mot de passe",
"employee.updatesecurityinfo.passwdcomplex": "Le mot de passe doit contenir des lettres, des chiffres et au moins un des symboles suivant ~!@##$%^&*",
"employee.updatepersonalinfo.provterreffdatemissing": "Veuillez préciser la date d’entrée en vigueur du changement de province de résidence.",
"employee.updatepersonalinfo.provterreffdatepast": "La date d’entrée en vigueur du changement de province de résidence ne doit pas être une date dans le passé.",
"employee.updatepersonalinfo.provterreffdatefuture": "Requested change of the state/province of residence is scheduled for ?1 (fr)",
//"employee.smokerstatus.waitapproval": "Request to change smoker status to ?1 effective ?2 has been submitted for approval.<br/>Your smoker status has not been changed in the system until proper authorization is issued by your plan administrator. If you have any questions about the subject please contact your plan administrator. Email with the change request has been sent to your plan administrator. (fr)",
"employee.smokerstatus.waitapproval": "Vous ou votre conjoint avez demandé un statut de ?1 en date du ?2.Â Votre demande a été soumise pour approbation. Veuillez communiquer avec l'administrateur de votre régime pour toutes questions.",
"employee.smokerstatus.change": "Vous ne pourrez changer votre statut de fumeur qu’une fois votre événement de la vie terminé.",

// //selections/empselections.cfc
"empselections.benefagetermin.note": "Benefit coverage is terminated at the age of ?1",
"empselections.benefagereduct.note": "Benefit coverage is reduced at the age of ?1",
"empselections.benfwaiver.note": "Benefit is on waiver",
"empselections.employee": "Employé",
"empselections.spouse": "Conjoint",
"empselections.dependent": "Personnes à charge",
"empselections.family": "Famille",
"empselections.coverage.period.cost": "Couverture ?1 - ?2 coût : ?3 ?4",
"empselections.coverage.period.cost.min": "Couverture ?1 ?2",
"empselections.param.period.1": "mensuelle",
"empselections.param.period.2": "hebdomadaire",
"empselections.param.period.3": "bi-hebdomadaire",
"empselections.param.period.4": "annuel",
"empselections.param.waived": "(refusée)",
"empselections.agereduct.note": "La protection réduira à ?1 à l’à¢ge de ?2 ans",
"empselections.agetermin.note": "La protection de cette option se termine à l’à¢ge de ?1 ans",
"empselections.requested": "Demandée: ?1 - Coût(s) mensuel(s) : ?2",
"empselections.approved": "Approuvée: ?1 - Coût(s) mensuel(s) : ?2",

"empselections.prevselopt.note": "Lors de la dernière année d’inscription, cette option a été choisie au ?1 ?2",
"empselections.prevenrollselopt.note": "Lors de la dernière année d’inscription, cette option a été choisie au ?1 ?2",
"empselections.param.prevselopt.s": "protection de",
"empselections.param.prevselopt.def": "coût de",

//"empselections.evidreq.note": "Des preuves d'assurabilité sont exigées pour augmenter votre couverture pour cette garantie. Veuillez vérifier auprès de votre administrateur de régime.",
"empselections.nem_supported.note": "Mise en garde – Preuves d'assurabilité exigées</br></br>Vous avez choisi une couverture qui requiert une preuve d'assurabilité. à€ la fin du processus d'inscription, vous devrez remplir un formulaire que vous ferez parvenir à la compagnie d'assurance avec votre demande. Votre demande de couverture sera 'en attente' jusqu'à ce qu'elle soit approuvée par la compagnie d'assurance. Entre temps, le maximum permis sans preuve d'assurabilité s'appliquera",
"empselections.nem_supported_details.note": "La protection n’a pas encore été approuvée par l'administrateur de régime et ne sera pas affichée dans le relevé des garanties du régime: <br />Demandée: ?1 - Coût(s) mensuel(les): ( ?4 ) <br />Approuvée: ?5 - Coût(s) mensuel(les): ( ?6 )",
"empselections.nem_evidfile_details.note": "<a href=?1>Cliquer ici</a> afin de télécharger la documentation de preuve d’assurabilité nécessaire, si vous désiriez augmenter votre protection maximale au montant indiqué",

"empselections.fsacontrib": "Inscrivez le montant de la cotisation ?1",
"empselections.fsaminmaxcontrib": "Cotisation minimale ?1 ?2, cotisation maximale ?3 ?2",
"empselections.prevselectedoption.note": "Cette option a été choisie auparavant ?1 ?2",
"empselections.prevenrollmentselectedoption.note": "Lors de la dernière année d’inscription, cette option a été choisie ?1 ?2",
"empselections.withcost": "au coût de ",


// /selections/unusedflexcredits.cfc
"selections.unusedflexcredits.param.1": "cotisation minimale ",
"selections.unusedflexcredits.param.3": "cotisation maximale ",
"selections.unusedflexcredits.cashlabel": "Encaissement ?1 ?2 ?3 ?4",
"selections.unusedflexcredits.hcsalabel": "Compte de frais médicaux (CFM) ?1 ?2 ?3 ?4",
"selections.unusedflexcredits.rrsplabel": "?1 ?2 ?3 ?4",
"selections.unusedflexcredits.rrspfile": "(<a href='?1' target='_blank'>Télécharger le document</a>)",
"selections.unusedflexcredits.rrspselectyourprog": "Choisir ?1 votre programme de retraite",
"selections.unusedflexcredits.unusedcreditslabel": "?1",
"selections.unusedflexcredits.unusedcreditsoptionslabel": "?1",

"life.derectDepositInfo": "DÉPÔT DIRECT",
"life.enjoyPeaceofMind": "Vous aurez l'esprit tranquille, sachant que vos remboursements seront déposés directement au compte de votre choix dans les trois jours ouvrables suivant la date de traitement de votre demande de règlement. De plus, vous continuerez à recevoir un relevé explicatif du remboursement ainsi qu'un avis de dépôt direct. ",
"life.directDeposit": "Le dépôt direct est  : ",
"life.reliable": "Fiable - aucun risque de perte, d’oubli ou de vol de chèques ou de retards postaux",
"life.completelyConfidential": "Strictement confidentiel",
"life.informative": "Informatif - un avis de dépôt et une explication des prestations vous sont envoyés immédiatement après votre paiement",
"life.familiar": "Familier – de nombreux employés reçoivent leur salaire par dépôt direct",
"life.convenient": "Pratique – pas besoin de perdre un temps précieux pour déposer les prestations dans une institution financière",
"life.instructions": "Directives",
"life.completeFieldsTransit": "Veuillez indiquer les numéros de succursale, d'institution et de compte tel qu'ils sont indiqués sur vos chèques (sans espace ni caractère spécial).",
"life.note": "Remarque",
"life.adviceFinancialInstitution": "Veuillez noter que l'adresse de l'institution financière est mise à jour chaque mois. En cas de changement au cours du mois, il se peut que l'information ne soit pas encore accessible ou mise à jour. ",
"life.authorization": "Autorisation",
"life.authorize": "En remplissant cette section, j'autorise la Standard Life à déposer mes prestations dans le compte bancaire indiqué. Je confirme que les renseignements indiqués sur la présente autorisation sont exacts et je conviens d’informer la Standard Life de tout changement. J'accepte que cette entente de dépôt direct puisse être résiliée par la Standard Life ou par moi-même en tout temps sur simple avis écrit ou verbal.",

"microsite.title" : "Votre régime flexible suit votre parcours",
"microsite.home" : "Accueil",
"microsite.open.enrolment.available" : "Une période d’<b>inscription</b> sera disponible",
"microsite.no.open.enrolment.available" : "", //Il n'y a pas de période d'inscription en cours",
"microsite.from" : "du",
"microsite.From" : "Du",
"microsite.to" : "au",
"microsite.enrolment.submitted" : "Votre <b>inscription</b> a déjà été soumise.",
"microsite.contact.administrator" : "Pour modifier votre <b>inscription</b>, contactez l'administrateur du régime.",
"microsite.choose.your.coverage" : "Choisissez vos protections d’assurances collectives.",
"microsite.no.completed.enrolments" : "Vous avez pas terminé les inscriptions.",
"microsite.view" : "Consulter",
"microsite.update" : "Mettez à jour",
"microsite.viewUpdate" : "Consultez et modifiez",
"microsite.my.life.events" : "Événements de ma vie ",
"microsite.my.coverage" : "Mes protections",
"microsite.my.activities" : "Mes activités",
"microsite.my.profile" : "Mon profil",
"microsite.my.dependents" : "Mes personnes à charge",
"microsite.add.remove.dependents" : "Mettez à jour les renseignements sur vos personnes à charge et choisissez vos garanties en fonction de votre événement de vie.",
"microsite.learn.about.selections" : "Consultez vos garanties courantes et précédentes.",
"microsite.learn.about.history" : "Consultez vos choix de garanties actuelles et précédentes",
"microsite.view.profile.information" : "Consultez et modifiez vos renseignements personnels tel que votre adresse, votre statut fumeur et vos renseignements bancaires.",
"microsite.view.dependents.information" : "Consultez et modifiez les renseignements sur vos personnes à charge, comme le statut étudiant de vos enfants et le statut fumeur de votre conjoint.",
"microsite.coverage.effective": "Date d'effet de vos protections ",
"microsite.employment.info": "Renseignements sur l'emploi",
"microsite.direct.deposit.info": "Dépôt direct",
"microsite.security": "Sécurité",
"microsite.edit.personal.information": "Modifier les renseignements personnels",
"microsite.dependents.note.text1" : "Pour ajouter ou supprimer une personne à charge, ou pour modifier les renseignements de l'assureur de votre conjoint, rendez-vous à la section <a href='#home/life-events'>Événements de ma vie</a> et suivez les directives.",
"microsite.dependents.note.text2" : "Pour modifier vos bénéficiaires, il vous suffit de remplir et signer le formulaire ",
"microsite.dependents.note.text3" : "Désignation de bénéficiaire",
"microsite.dependents.note.text4" : " et le retourner à votre administrateur de régime.",

"life-events.contact.admin": "My life events",
"life-events.info": "Mettez à jour les renseignements sur vos personnes à charge et choisissez vos garanties en fonction de votre événement de la vie.",
"life-events.definition": "Definition",
"life-events.matrimonialChange": "Matrimonial change",
"life-events.matrimonialChange.details": "(marriage, common-law spouse, divorce, widow, etc.)",
"life-events.additionDependentChild": "Addition of a dependent child",
"life-events.additionDependentChild.details": "(newborn, adoption, etc.)",
"life-events.removalDependentChild": "Removal of a dependent",
"life-events.removalDependentChild.details": "(child no longer eligible, etc.)",
"life-events.spouseModification": "Spouse coverage modification with another carrier",
"life-events.spouseModification.details": "(spouse no longer covered by another carrier, etc.)",
"life-events.note": "Remarque",
"life-events.guideline": "text box open (at plan setup) to give guidelines to the employee",
"life-events.effectiveDate": "Life event effective date",
"life-events.enrolment.open": "Période d’inscription en cours: ",
"life-events.enrolment.period": "?1 au ?2",
"emplifeevents.lifeevent.note": "<p>Vous devez déclarer vos événements de la vie dans les ?1 ?2 suivant leur date d'effet. Une fois que vous aurez entré les renseignements demandés ci-dessus, vous aurez ?3 ?4 pour revoir vos protections et faire les changements nécessaires.</p><p>Selon votre événement de la vie, vous voudrez peut-être modifier les bénéficiaires que vous avez désignés. Pour ce faire, il vous suffit de remplir et de signer le ?5 et de le retourner à l'administrateur de votre régime.</p><p>Veuillez communiquer avec l'administrateur de votre régime pour toutes questions au sujet des événements de la vie admissibles et des changements que vous désirez apporter à vos protections.</p>",
"emplifeevents.lifeevent.added.note":"<p>Une fois que vous aurez entré les renseignements demandées ci-dessus, vous aurez ?1 ?2 pour revoir vos protections et faire les changements nécessaires.</p><p>Selon votre événement de la vie, vous voudrez peut-être modifier les bénéficiaires que vous avez désignés. Pour ce faire, il vous suffit de remplir et de signer le formulaire ?3 et de le retourner à l'administrateur de votre régime.</p><p>Veuillez communiquer avec l'administrateur de votre régime pour toutes questions au sujet des événements de la vie admissibles et des changements que vous désirez apporter à vos protections.</p>",
"emplifeevents.lifeevent.notezerograce": "",	// leave it empty for now and take following out: <p>Votre événement de la vie doit être approuvé par l'administrateur de votre régime.</p><p>Selon votre événement de la vie, vous voudrez peut-être modifier les bénéficiaires que vous avez désignés. Pour ce faire, il vous suffit de remplir et de signer le formulaire ?1 et de le retourner à l'administrateur de votre régime.</p><p>Veuillez communiquer avec l'administrateur de votre régime pour toutes questions au sujet des événements de la vie admissibles et des changements que vous désirez apporter à vos protections.</p>

"emplifeevents.lifeevent.note.nobeneficiary": "<p>Vous devez déclarer vos événements de la vie dans les ?1 ?2 suivant leur date d'effet. Une fois que vous aurez entré les renseignements demandés ci-dessus, vous aurez ?3 ?4 pour revoir vos protections et faire les changements nécessaires.</p><p>Selon votre événement de la vie, vous voudrez peut-être modifier les bénéficiaires que vous avez désignés. Pour ce faire, il vous suffit de remplir et de signer le bénéficiaire et de le retourner à l'administrateur de votre régime.</p><p>Veuillez communiquer avec l'administrateur de votre régime pour toutes questions au sujet des événements de la vie admissibles et des changements que vous désirez apporter à vos protections.</p>",
"emplifeevents.lifeevent.added.note.nobeneficiary":"<p>Une fois que vous aurez entré les renseignements demandées ci-dessus, vous aurez ?1 ?2 pour revoir vos protections et faire les changements nécessaires.</p><p>Selon votre événement de la vie, vous voudrez peut-être modifier les bénéficiaires que vous avez désignés. Pour ce faire, il vous suffit de remplir et de signer le formulaire bénéficiaire et de le retourner à l'administrateur de votre régime.</p><p>Veuillez communiquer avec l'administrateur de votre régime pour toutes questions au sujet des événements de la vie admissibles et des changements que vous désirez apporter à vos protections.</p>",
"emplifeevents.lifeevent.notezerograce.nobeneficiary": "",

"emplifeevents.beneficiaryDesignation": "Désignation de bénéficiaire",
"life-events.note.detail3": "For beneficiary modification, print the ",
"life-events.note.detail4": "Beneficiary designation ",
"life-events.note.detail5": "form, complete, sign and return it to Standard Life.",
"life-events.definition.text": "A major event that changes a person's status or circumstances, such as giving birth, adoption, marriage, divorce, death of spouse, death of dependent child, etc. When such event occurs, you are allowed to modify your coverage outside the official re-enrolment periods. (fr)",

"life-events.summary.current.waiting.approval": "En attente d'approbation",
"life-events.summary.current.approved": "Approuvé",
"emplifeevents.lifeevent.period.day": "jours",
"emplifeevents.lifeevent.period.week": "semaines",
"emplifeevents.lifeevent.period.month": "mois",
"life-events.inProgress": "Événement de vie en cours",
"life-events.eventDescription": "Description de l’événement: ",
"life-events.requestDate": "Date de la demande: ",
"life-events.effectiveDate2": "Date d’effet de l’événement: ",
"life-events.submissionDate": "Date de la transmission: ",
"life-events.status": "Statut: ",
"life-events.warning": "Avertissement",
"life-events.warning1": "Une période d'inscription est présentement en cours. La section Mes événements de vie sera disponible lorsque la période d’inscription courante sera terminée.",
"life-events.warning2": "Si vous avez besoin d’effectuer un changement relativement à votre événement de la vie, veuillez contacter votre administrateur du régime.",
"life-events.warning3": "Veuillez communiquer avec l'administrateur de votre régime pour toutes questions sur un événement de la vie ou pour modifier vos choix.",
"life-events.warning4": "Vous avez demandé un changement qui nécessite l'approbation de l'administrateur de votre régime. Une fois approuvé, vous pourrez effectuer votre demande d'événement de la vie.",
"life-events.next": "Suivant",
"life-events.choose": "Choisissez votre événement de la vie",
"life-events.confirmationSecurity": "Voulez-vous mettre à jour vos questions de sécurité?",
"life-events.confirmationBanking": "Voulez-vous mettre à jour vos renseignements bancaires?",
"life-events.myDependents.text": "<p>Mettez à jour les renseignements sur vos personnes à charge et choisissez vos garanties en fonction de votre événement de la vie.</p><p>Les modifications prendront effet à la date effective de votre événement de la vie.</p>",
"life-events.event.effective": "Date d’effet ",
"emplifeevents.lifeevent.compare.text": "You may <b>keep your current</b> selections or <b>modify</b> them.  (fr)",
"emplifeevents.lifeevent.compare.note": "You have until the end of the enrolment period ?1 to submit your Life event. Otherwise, your current selections will be reconducted at the end of the enrolment period. (fr)",
"emplifeevents.lifeevent.compare.view": "View my current selections (fr)",
"emplifeevents.lifeevent.compare.keep.selections.description": "This action will submit your life event (fr)",
"emplifeevents.lifeevent.compare.modify.selections.description": "This action will open My benefits for modification (fr)",
"required.fieldsInvalidDateErrorText": "La date de naissance que vous avez entré semble incorrecte car elle ne peut être supérieure à la date d'effet de l'événement de la vie.",
"emplifeevents.lifeevent.zerograceperiods.contactplanadmin": "Veuillez communiquer avec l'administrateur de votre régime pour toutes questions au sujet des événements de la vie admissibles et des changements que vous désirez apporter à vos protections.",
"emplifeevents.addlifeevent.currenrollnotauthorized": "Veuillez communiquer avec l'administrateur de votre régime au sujet des changements que vous désirez apporter à vos protections.",

"header.planWorkbook.description": "Sommaire de votre régime d'avantages sociaux flexible fourni par le titulaire de la police",
"enrollNow.personal.groupInsuranceBooklet.description": "Indique les renseignements sur votre régime d'assurances collectives",
"header.glossary.description": "Glossaire de l'assurance collective",
"header.tutorial.description": "Tutoriel pour vous aider à effectuer plusieurs types d’opérations",
"header.beneficiary.designation.form": "formulaire désignation de bénéficiaire",
"last.pdf": " (PDF)",
"available.forms": "Formulaires disponibles",
"benefit.information.change": "Les renseignements relatifs à la coordination des prestations ne peuvent être modifiés qu’à partir de la section Événements de ma vie.",
"life_events.nofuturedate":"Veuillez ne pas inscrire de dates futures pour votre événement de la vie.",
"life-events.enrollment.ended": "Votre période d'inscription est maintenant terminée, veuillez contacter votre administrateur du régime.",
"life-events.summary.current.not.completed": "En cours",

"life_events.predateLifeEvent":"La date que vous avez entrée est antérieure à un événement de la vie déjà terminé.",

//Tutorials Page
"choose_coverage":"Comment choisir vos protections",
"renew_coverage":"Comment renouveler vos choix de protection",
"change_personal_info":"Comment modifier vos renseignements personnels (adresse, courriel)",
"change_smoking_status":"Comment changer votre statut fumeur",
"change_deposit_information":"Comment modifier vos renseignements sur le dépôt direct",
"change_your_password":"Comment changer votre mot de passe",
"view_dependent_information":"Comment consulter les renseignements sur vos personnes à charge",
"view_benefit_summary":"Comment consulter votre Sommaire des garanties",

"password_common_error": "Le mot de passe ne respecte pas les règles de complexité de mot de passe décrites ci-dessous",
"password_space_error": "Please do not enter spaces",
"password_mirror_error": "Password cannot be same as username",
"same_password_error": "Votre nouveau mot de passe ne peut pas être le même que votre ancien mot de passe",
"coverage_page_warning": "Vos protections actuelles seront disponibles une fois que votre événement de la vie sera terminé",
"coverage_page_warning_incomplete": "Votre couverture actuelle sera disponible une fois terminé",
"dependent_screen_text": "Veuillez vous assurer que les informations inscrites pour vos personnes à charge sont exactes avant de sauvegarder",

"perform_life_event": "Comment effectuer un événement de la vie",

"call_us_now": "Appelez nous",
"email_us": "Nous joindre", 
"employee_login": "Renseignements d'ouverture de session",


//Registeration Page
"empregister":"Enregistrer",
"empregister.already.registered": "Vous êtes déjà inscrit",
"empregister.employee.notfound": "Votre compte n'a pas ete trouve, s'il vous plait contactez votre administrateur du regime",
"empregister.missing.requiredfield": "Ce champ est obligatoire",
"empregister.invalid.email": "S'il vous plait entrer une adresse courriel valide",
"empregister.invalid.birthdate": "La date doit etre valid et indiquee salon le format suivant: mm/jj/aaaa",
"empregister.firstname": "Prénom",
"empregister.lastname": "Nom",
"empregister.email.address": "Courriel",
"empregister.postalcode": "Code postal",
"empregister.dateofbirth": "Date de naissance",
"empregister.username":"User Name",
"empregister.expired":"Votre activation a expire. Veuillez communiquer avec votre administrateur de regime.",
"empregister.invalid.birthdaterange":"S'il vous plait verifier le champ de la date.",


//Scenario Comparison Page
"scenario.comparison":"Comparaison",
"scenario.overview":"Sommaire",
"scenario.benefits":"Votre couverture",
"scenario.legend":"Description",
"scenario.unapproved.cost":"coût non approuvé",
"scenario.unapproved.coverage":"couverture non approuvé",
"scenario.confirm": "En choisissant ce scénario, tous les autres scénarios seront supprimés",

"login.usernamemail.nomatch": "Nom d'utilisateur et courriel ne correspondent pas. S'il vous plaît , entrez à nouveau ou contactez votre administrateur du régime.",
"select.scenario": "Choisissez l'option",
"add.scenario": "AJOUTER SCÉNARIO",
"edit.scenario": "MODIFIER SCÉNARIO",
"forgotpassword.nosecurityquestions":"Informations de mot de passe a été envoyé",
"empresQs":"S'il vous plaît valider vos informations",
"empreset.incorrectform":"S'il vous plaît revérifier les détails",
"login.usernamemail.noquestionset":"Veuillez communiquer avec votre administrateur de regime",
"security.answer.maxlength":"Réponse ne peut pas dépasser 200 caractères"
//////////////////////////////////
// Do not edit below this line  //
//////////////////////////////////
};
return exports;
});
